# Copyright (c) 2025 Cisco Systems, Inc. All Rights Reserved

[project]
name = "cisco-ise-mcp-server"
version = "1.0.0"
description = "MCP Server for Cisco ISE"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "defusedxml==0.7.1",
    "dotenv==0.9.9",
    "fastmcp>=3.4.7,<4",
    "httpx==0.28.1",
    "mcp>=1.28.1,<2",
    "jaydebeapi==1.2.3",
    "JPype1==1.6.0",
    "pydantic==2.12.5",
    "pydantic-settings>=2.14.2,<3",
    "shared-libs",
    "structlog==25.5.0",
]

[tool.uv.sources]
shared-libs = { path = "shared_libs", editable = true }

[dependency-groups]
dev = [
    "openapi-python-client==0.28.1",
    "debugpy==1.8.19",
    "pytest==8.3.5",
    "pytest_asyncio==1.3.0",
    "pytest-cov==7.0.0",
]
