openapi: 3.0.3
info:
  title: Deployment
  description: APIs for the configuration, administration and monitoring of the nodes in a Cisco ISE cluster deployment.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    email: cs-ise-api@cisco.com
  version: v3-oas3
paths:
  /deployment/node:
    get:
      summary: Retrieve the list of all the nodes that are deployed in the cluster.
      operationId: getDeploymentNodes
      description: |
        The API lists all the nodes that are deployed in the cluster.<br>
        Returns basic information about each of the deployed nodes in the cluster like hostname, status, roles, and services. <br>
        Supports filtering on FQDN, hostname, IP address, roles, services and node status.
      tags:
        - Node Deployment
      parameters:
        - $ref: '#/components/parameters/filtering'
        - $ref: '#/components/parameters/filtertype'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentNodesResponse'
        '400':
          description: |
            Invalid inputs have been supplied.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  parameters:
    filtering:
      name: filter
      in: query
      required: false
      description: '<div> <style type="text/css" scoped> .apiServiceTable td, .apiServiceTable th { padding: 5px 10px !important; text-align: left; } </style> <span> <b>Simple filtering</b> is available through the filter query string parameter. The structure of a filter is a triplet of field operator and value, separated by dots. More than one filter can be sent. The logical operator common to all filter criteria is AND by default, and can be changed by using the <i>"filterType=or"</i> query string parameter. Each resource Data model description should specify if an attribute is a filtered field. </span> <br /> <table class="apiServiceTable"> <thead> <tr> <th>OPERATOR</th> <th>DESCRIPTION</th> </tr> </thead> <tbody> <tr> <td>EQ</td> <td>Equals</td> </tr> <tr> <td>NEQ</td> <td>Not Equals</td> </tr> <tr> <td>STARTSW</td> <td>Starts With</td> </tr> <tr> <td>NSTARTSW</td> <td>Not Starts With</td> </tr> <tr> <td>ENDSW</td> <td>Ends With</td> </tr> <tr> <td>NENDSW</td> <td>Not Ends With</td> </tr> <tr> <td>CONTAINS</td> <td>Contains</td> </tr> <tr> <td>NCONTAINS</td> <td>Not Contains</td> </tr> </tbody> </table> </div>'
      schema:
        type: array
        items:
          type: string
      style: form
      allowReserved: true
    filtertype:
      name: filterType
      in: query
      description: The logical operator common to all filter criteria is AND by default, and can be changed by using this parameter.
      required: false
      schema:
        type: string
        enum:
          - AND
          - OR
        default: AND
  schemas:
    DeploymentNode:
      type: object
      properties:
        hostname:
          pattern: '[a-zA-Z][\w\-]*'
          maxLength: 64
          minLength: 1
          type: string
          example: isenode
        fqdn:
          $ref: '#/components/schemas/FQDN'
        ipAddress:
          $ref: '#/components/schemas/IPAddress'
        roles:
          $ref: '#/components/schemas/Roles'
        services:
          $ref: '#/components/schemas/Services'
        nodeStatus:
          $ref: '#/components/schemas/NodeStatus'
      required:
        - hostname
        - fqdn
        - ipAddress
        - services
      example: TBD
    DeploymentNodesResponse:
      type: object
      properties:
        response:
          type: array
          items:
            $ref: '#/components/schemas/DeploymentNode'
          example: TBD
        version:
          type: string
          example: 1.0.0
    ErrorResponse:
      type: object
      properties:
        error:
          $ref: '#/components/schemas/Message'
        version:
          type: string
          example: 1.0.0
    FQDN:
      maxLength: 64
      minLength: 1
      pattern: ^(?=.{2,255}$)[0-9A-Za-z](?:(?:[0-9A-Za-z]|-|_){0,61}[0-9A-Za-z])?(?:\.[0-9A-Za-z](?:(?:[0-9A-Za-z]|-|_){0,61}[0-9A-Za-z])?)*(?:\.[A-Za-z](?:(?:[A-Za-z]|-){0,61}[A-Za-z])?)+\.?$
      type: string
    IPAddress:
      type: string
      format: ipv4 | ipv6
    Message:
      type: object
      properties:
        message:
          type: string
          example: Success
    NodeStatus:
      type: string
      enum:
        - Connected
        - Disconnected
        - InProgress
        - ReplicationStopped
        - RegistrationFailed
        - NotInSync
        - NotUpgraded
        - NotApplicable
    Roles:
      type: array
      items:
        type: string
        enum:
          - PrimaryAdmin
          - SecondaryAdmin
          - PrimaryMonitoring
          - SecondaryMonitoring
          - PrimaryDedicatedMonitoring
          - SecondaryDedicatedMonitoring
          - Standalone
    Services:
      type: array
      items:
        type: string
        enum:
          - Session
          - Profiler
          - TC-NAC
          - SXP
          - DeviceAdmin
          - PassiveIdentity
          - pxGrid
          - pxGridCloud
