# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

import json
import os
import sys
from pathlib import Path
from unittest.mock import AsyncMock, Mock, patch
import types

import pydantic_core
import pytest

pytest_plugins = ("pytest_asyncio",)


class _DummyFastMCP:
    """Minimal stand-in for FastMCP used during unit tests."""

    def __init__(self, *_args, **_kwargs):
        pass

    def tool(self, _func=None, **_kwargs):
        def decorator(func):
            class _DummyTool:
                def __init__(self, fn):
                    self.fn = fn

                def __call__(self, *args, **kwargs):
                    return self.fn(*args, **kwargs)

            return _DummyTool(func)

        return decorator if _func is None else decorator(_func)

    def run(self, *_args, **_kwargs):
        pass


try:
    from fastmcp import FastMCP as _RealFastMCP  # noqa: F401
    from fastmcp.exceptions import ToolError as _RealToolError  # noqa: F401
except ImportError:
    _RealFastMCP = None  # type: ignore[assignment]
    _RealToolError = None  # type: ignore[assignment]

    _fastmcp_mod = types.ModuleType("fastmcp")
    _fastmcp_mod.__path__ = []  # type: ignore[attr-defined]
    _fastmcp_mod.FastMCP = _DummyFastMCP  # type: ignore[attr-defined]

    _exceptions_mod = types.ModuleType("fastmcp.exceptions")

    class _DummyToolError(Exception):
        """Stand-in for fastmcp.exceptions.ToolError."""

    _exceptions_mod.ToolError = _DummyToolError  # type: ignore[attr-defined]

    sys.modules["fastmcp"] = _fastmcp_mod
    sys.modules["fastmcp.exceptions"] = _exceptions_mod


class _DummyAuthenticatedClient:
    def __init__(self, *_args, **_kwargs):
        pass

# TODO: check how to replace this with a real module
def _ensure_module(name: str) -> types.ModuleType:
    module = sys.modules.get(name)
    if module is None:
        module = types.ModuleType(name)
        module.__path__ = []  # type: ignore[attr-defined]
        sys.modules[name] = module
    return module


# Ensure the project root is importable before we decide whether the real
# autogenerated_api_clients package is available.
PROJECT_DIR = Path(__file__).resolve().parent.parent
if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

# Prefer the real generated clients when they are importable: installing
# fake stand-ins into sys.modules leaks across test files (sys.modules is
# process-wide) and can shadow the real modules other test files rely on.
# Only fall back to stubs when the real package cannot be imported.
try:
    import autogenerated_api_clients  # noqa: F401

    _USE_API_CLIENT_STUBS = False
except ImportError:
    _USE_API_CLIENT_STUBS = True

if _USE_API_CLIENT_STUBS:
    _ensure_module("autogenerated_api_clients")
for _subpkg in [] if not _USE_API_CLIENT_STUBS else [
    "endpoints",
    "certificates",
    "policy",
    "patch_and_upgrade",
    "deployment",
]:
    pkg_name = f"autogenerated_api_clients.{_subpkg}"
    _ensure_module(pkg_name)
    client_module = _ensure_module(f"{pkg_name}.client")
    setattr(client_module, "AuthenticatedClient", _DummyAuthenticatedClient)

    if _subpkg == "endpoints":
        models_pkg = _ensure_module(f"{pkg_name}.models")

        filter_module = _ensure_module(
            f"{models_pkg.__name__}.get_endpoints_filter_type"
        )

        class _DummyGetEndpointsFilterType:
            AND = "AND"
            OR = "OR"

        setattr(filter_module, "GetEndpointsFilterType", _DummyGetEndpointsFilterType)

        sort_module = _ensure_module(f"{models_pkg.__name__}.get_endpoints_sort")

        class _DummyGetEndpointsSort:
            ASC = "asc"
            DESC = "desc"

        setattr(sort_module, "GetEndpointsSort", _DummyGetEndpointsSort)

        openapi_module = _ensure_module(f"{models_pkg.__name__}.open_api_endpoint")

        class _DummyOpenAPIEndpoint:
            def __init__(self, **data):
                self._data = data

            def to_dict(self):
                return self._data

        setattr(openapi_module, "OpenAPIEndpoint", _DummyOpenAPIEndpoint)

        types_module = _ensure_module(f"{pkg_name}.types")

        class _DummyUnset:
            pass

        setattr(types_module, "Unset", _DummyUnset)
        setattr(types_module, "UNSET", _DummyUnset())

        api_pkg = _ensure_module(f"{pkg_name}.api")
        endpoints_module = _ensure_module(f"{api_pkg.__name__}.endpoints")

        def _create_api_operation():
            async def _dummy_asyncio_detailed(*_args, **_kwargs):
                return types.SimpleNamespace(status_code=200, content=b"{}")

            return types.SimpleNamespace(asyncio_detailed=_dummy_asyncio_detailed)

        for _operation in [
            "get_endpoints",
            "get_endpoint_by_id",
            "get_rejected_endpoints",
            "get_device_type_summary",
        ]:
            setattr(endpoints_module, _operation, _create_api_operation())

    if _subpkg == "certificates":
        models_pkg = _ensure_module(f"{pkg_name}.models")

        filter_module = _ensure_module(
            f"{models_pkg.__name__}.get_trusted_certificates_filter_type"
        )

        class _DummyGetTrustedCertificatesFilterType:
            AND = "AND"
            OR = "OR"

        setattr(
            filter_module,
            "GetTrustedCertificatesFilterType",
            _DummyGetTrustedCertificatesFilterType,
        )

        sort_module = _ensure_module(
            f"{models_pkg.__name__}.get_trusted_certificates_sort"
        )

        class _DummyGetTrustedCertificatesSort:
            ASC = "asc"
            DESC = "desc"

        setattr(
            sort_module,
            "GetTrustedCertificatesSort",
            _DummyGetTrustedCertificatesSort,
        )

        response_module = _ensure_module(
            f"{models_pkg.__name__}.trust_certificate_response"
        )

        class _DummyTrustCertificateResponse:
            @classmethod
            def from_dict(cls, data):
                instance = cls()
                instance.__dict__.update(data)
                return instance

        setattr(
            response_module,
            "TrustCertificateResponse",
            _DummyTrustCertificateResponse,
        )

        types_module = _ensure_module(f"{pkg_name}.types")

        class _DummyUnset:
            pass

        setattr(types_module, "Unset", _DummyUnset)
        setattr(types_module, "UNSET", _DummyUnset())

        api_pkg = _ensure_module(f"{pkg_name}.api")
        certificates_module = _ensure_module(f"{api_pkg.__name__}.certificates")

        def _create_cert_operation():
            async def _dummy_asyncio_detailed(*_args, **_kwargs):
                return types.SimpleNamespace(status_code=200, content=b"{}")

            return types.SimpleNamespace(asyncio_detailed=_dummy_asyncio_detailed)

        for _operation in [
            "get_cs_rs",
            "get_csr_by_id",
            "get_trusted_certificates",
            "get_trusted_certificate_by_id",
            "get_system_certificates",
            "get_system_certificate_by_id",
            "export_trusted_cert",
            "export_csr",
        ]:
            setattr(certificates_module, _operation, _create_cert_operation())

    if _subpkg == "patch_and_upgrade":
        api_pkg = _ensure_module(f"{pkg_name}.api")
        patch_module = _ensure_module(f"{api_pkg.__name__}.patch")

        def _create_patch_operation():
            async def _dummy_asyncio_detailed(*_args, **_kwargs):
                return types.SimpleNamespace(status_code=200, content=b"{}")

            return types.SimpleNamespace(asyncio_detailed=_dummy_asyncio_detailed)

        for _operation in [
            "get_installed_patches",
            "patch_rollback_info",
        ]:
            setattr(patch_module, _operation, _create_patch_operation())

    if _subpkg == "deployment":
        models_pkg = _ensure_module(f"{pkg_name}.models")

        filter_module = _ensure_module(
            f"{models_pkg.__name__}.get_deployment_nodes_filter_type"
        )

        class _DummyGetDeploymentNodesFilterType:
            AND = "AND"
            OR = "OR"

        setattr(
            filter_module,
            "GetDeploymentNodesFilterType",
            _DummyGetDeploymentNodesFilterType,
        )

        types_module = _ensure_module(f"{pkg_name}.types")

        class _DummyUnset:
            pass

        setattr(types_module, "Unset", _DummyUnset)
        setattr(types_module, "UNSET", _DummyUnset())

        api_pkg = _ensure_module(f"{pkg_name}.api")
        node_deployment_module = _ensure_module(f"{api_pkg.__name__}.node_deployment")

        def _create_deployment_operation():
            async def _dummy_asyncio_detailed(*_args, **_kwargs):
                return types.SimpleNamespace(status_code=200, content=b"{}")

            return types.SimpleNamespace(asyncio_detailed=_dummy_asyncio_detailed)

        setattr(
            node_deployment_module,
            "get_deployment_nodes",
            _create_deployment_operation(),
        )

    if _subpkg == "policy":
        api_pkg = _ensure_module(f"{pkg_name}.api")

        def _create_policy_operation():
            async def _dummy_asyncio_detailed(*_args, **_kwargs):
                return types.SimpleNamespace(status_code=200, content=b"{}")
            return types.SimpleNamespace(asyncio_detailed=_dummy_asyncio_detailed)

        # Map each policy API module to the operations imported by
        # tools/policy_tool_handler.py. Keep in sync with that file's imports.
        _policy_api_operations = {
            "network_access_policy_sets": [
                "get_network_access_policy_set_list",
                "get_network_access_policy_set_by_id",
            ],
            "network_access_authentication_rules": [
                "get_network_access_policy_by_id_authentication_rule_list",
            ],
            "network_access_authorization_rules": [
                "get_network_access_policy_by_id_authorization_rule_list",
            ],
            "network_access_authorization_exception_rules": [
                "get_network_access_policy_by_id_local_exception_rule_list",
            ],
            "network_access_authorization_global_exception_rules": [
                "get_network_access_policy_set_global_exception_rule_list",
            ],
            "network_access_authorization_profiles": [
                "get_network_access_profiles",
            ],
            "network_access_conditions": [
                "get_network_access_conditions",
                "get_network_access_conditions_for_policy_set",
                "get_network_access_conditions_for_authentication_rule",
                "get_network_access_conditions_for_authorization_rule",
            ],
            "network_access_identity_stores": [
                "get_network_access_identity_stores",
            ],
            "network_access_security_groups": [
                "get_network_access_security_groups",
            ],
            "network_access_service_names": [
                "get_network_access_service_names",
            ],
        }

        for _module_name, _operations in _policy_api_operations.items():
            policy_module = _ensure_module(f"{api_pkg.__name__}.{_module_name}")
            for _operation in _operations:
                setattr(policy_module, _operation, _create_policy_operation())


class TestBaseToolHandlerTransientErrors:
    """Unit tests for BaseToolHandler.execute_api_call transient-error handling."""

    @staticmethod
    def _make_handler():
        from tools.base_tool_handler import BaseToolHandler
        from clients.client_factory import ClientFactory, ClientName

        factory = Mock(spec=ClientFactory)
        factory.get_client.return_value = Mock()
        return BaseToolHandler(ClientName.POLICY, factory)

    @pytest.mark.asyncio
    async def test_connect_error_raises_ise_unreachable_with_retry(self):
        import httpx
        from fastmcp.exceptions import ToolError as McpToolError

        handler = self._make_handler()
        failing_fn = AsyncMock(side_effect=httpx.ConnectError("connection refused"))

        with pytest.raises(McpToolError) as exc_info:
            await handler.execute_api_call(failing_fn, "test_op")

        data = json.loads(str(exc_info.value))
        assert data["error_category"] == "external_error"
        assert data["error_code"] == "ISE_UNREACHABLE"
        assert data["retry"] is True
        assert "test_op" in data["message"]

    @pytest.mark.asyncio
    async def test_timeout_raises_ise_unreachable_with_retry(self):
        import httpx
        from fastmcp.exceptions import ToolError as McpToolError

        handler = self._make_handler()
        failing_fn = AsyncMock(side_effect=httpx.ReadTimeout("read timed out"))

        with pytest.raises(McpToolError) as exc_info:
            await handler.execute_api_call(failing_fn, "slow_op")

        data = json.loads(str(exc_info.value))
        assert data["error_category"] == "external_error"
        assert data["error_code"] == "ISE_UNREACHABLE"
        assert data["retry"] is True
        assert "slow_op" in data["message"]

    @pytest.mark.asyncio
    async def test_generic_exception_still_raises_ise_api_error(self):
        from fastmcp.exceptions import ToolError as McpToolError

        handler = self._make_handler()
        failing_fn = AsyncMock(side_effect=RuntimeError("unexpected"))

        with pytest.raises(McpToolError) as exc_info:
            await handler.execute_api_call(failing_fn, "broken_op")

        data = json.loads(str(exc_info.value))
        assert data["error_category"] == "external_error"
        assert data["error_code"] == "ISE_API_ERROR"
        assert data["retry"] is False
        assert "broken_op" in data["message"]

    @pytest.mark.asyncio
    async def test_empty_body_raises_invalid_response(self):
        from fastmcp.exceptions import ToolError as McpToolError

        handler = self._make_handler()
        mock_response = Mock(status_code=200, content=b"")
        api_fn = AsyncMock(return_value=mock_response)

        with pytest.raises(McpToolError) as exc_info:
            await handler.execute_api_call(api_fn, "empty_body_op")

        data = json.loads(str(exc_info.value))
        assert data["error_category"] == "external_error"
        assert data["error_code"] == "ISE_INVALID_RESPONSE"
        assert data["retry"] is False
        assert "empty_body_op" in data["message"]
        assert "200" in data["message"]

    @pytest.mark.asyncio
    async def test_non_json_body_raises_invalid_response(self):
        from fastmcp.exceptions import ToolError as McpToolError

        handler = self._make_handler()
        mock_response = Mock(status_code=200, content=b"<html>Error</html>")
        api_fn = AsyncMock(return_value=mock_response)

        with pytest.raises(McpToolError) as exc_info:
            await handler.execute_api_call(api_fn, "html_body_op")

        data = json.loads(str(exc_info.value))
        assert data["error_category"] == "external_error"
        assert data["error_code"] == "ISE_INVALID_RESPONSE"
        assert data["retry"] is False
        assert "html_body_op" in data["message"]
        assert "200" in data["message"]

    @pytest.mark.asyncio
    async def test_4xx_response_raises_ise_api_error_no_retry(self):
        from fastmcp.exceptions import ToolError as McpToolError

        handler = self._make_handler()
        mock_response = Mock(status_code=403, content=b"Forbidden")
        api_fn = AsyncMock(return_value=mock_response)

        with pytest.raises(McpToolError) as exc_info:
            await handler.execute_api_call(api_fn, "forbidden_op")

        data = json.loads(str(exc_info.value))
        assert data["error_category"] == "external_error"
        assert data["error_code"] == "ISE_API_ERROR"
        assert data["retry"] is False
        assert "403" in data["message"]
        assert "forbidden_op" in data["message"]

    @pytest.mark.asyncio
    async def test_5xx_response_raises_ise_api_error_with_retry(self):
        from fastmcp.exceptions import ToolError as McpToolError

        handler = self._make_handler()
        mock_response = Mock(status_code=502, content=b"Bad Gateway")
        api_fn = AsyncMock(return_value=mock_response)

        with pytest.raises(McpToolError) as exc_info:
            await handler.execute_api_call(api_fn, "gateway_op")

        data = json.loads(str(exc_info.value))
        assert data["error_category"] == "external_error"
        assert data["error_code"] == "ISE_API_ERROR"
        assert data["retry"] is True
        assert "502" in data["message"]
        assert "gateway_op" in data["message"]


class TestMain:
    """Unit tests for server.main."""

    def test_main_success(self):
        with patch("server.ise_mcp_server") as mock_server, patch(
            "server.logger"
        ) as mock_logger:
            mock_server.run = Mock()

            from server import main

            exit_code = main()

            mock_logger.info.assert_called_with("Starting ISE MCP Server...")
            mock_server.run.assert_called_once_with(
                transport="streamable-http",
                host="0.0.0.0",
                port=5000,
            )
            assert exit_code == 0

    def test_main_exception(self):
        with patch("server.ise_mcp_server") as mock_server, patch(
            "server.logger"
        ) as mock_logger:
            mock_server.run = Mock(side_effect=RuntimeError("fail"))

            from server import main

            exit_code = main()

            mock_logger.exception.assert_called()
            assert exit_code == 1


class TestSessionTools:
    """Unit tests for session-related MCP tools."""

    @pytest.mark.asyncio
    async def test_active_sessions_search_delegates_to_handler(self):
        from models.session_models import ActiveSessionSearchResult

        with patch("server.session_tool_handler") as mock_handler:
            mock_return = ActiveSessionSearchResult(
                search_filters={"minutes": 720},
                total_matching_sessions=5,
                sample_size=3,
                sample_sessions=[],
                sampling_note=(
                    "This is a SAMPLE of 3 out of 5 matching sessions, capped by the result limit. Treat it as a representative example, not an exhaustive list."
                ),
            )
            mock_handler.search_active_sessions = AsyncMock(return_value=mock_return)

            from server import active_sessions_search

            result = await active_sessions_search(
                username="alice", nas_ip_address="10.0.0.1", minutes=720, limit=15
            )

            mock_handler.search_active_sessions.assert_called_once()
            kw = mock_handler.search_active_sessions.call_args[1]
            assert kw["username"] == "alice"
            assert kw["nas_ip_address"] == "10.0.0.1"
            assert kw["minutes"] == 720
            assert kw["limit"] == 15
            # The tool now returns the typed model directly so FastMCP can
            # advertise an outputSchema and populate structuredContent.
            assert isinstance(result, ActiveSessionSearchResult)
            assert result is mock_return
            # Structured serialization must still drop None fields, matching
            # the previous model_dump_json(exclude_none=True) wire format.
            data = pydantic_core.to_jsonable_python(result)
            assert data["total_matching_sessions"] == 5
            assert data["sample_size"] == 3
            assert "SAMPLE" in data["sampling_note"]

    @pytest.mark.asyncio
    async def test_active_sessions_search_default_params(self):
        from models.session_models import ActiveSessionSearchResult

        with patch("server.session_tool_handler") as mock_handler:
            mock_handler.search_active_sessions = AsyncMock(
                return_value=ActiveSessionSearchResult(
                    total_matching_sessions=0,
                    sample_size=0,
                    sample_sessions=[],
                )
            )

            from server import active_sessions_search

            await active_sessions_search()

            kw = mock_handler.search_active_sessions.call_args[1]
            assert kw["username"] is None
            assert kw["calling_station_id"] is None
            assert kw["nas_ip_address"] is None
            assert kw["framed_ip_address"] is None
            assert kw["server"] is None
            assert kw["minutes"] == 60
            assert kw["limit"] == 10

    @pytest.mark.asyncio
    async def test_sessions_search_with_advanced_details_tool(self):
        from models.session_models import EnrichedSessionSearchResult

        with patch("server.session_tool_handler") as mock_handler:
            mock_return = EnrichedSessionSearchResult(
                search_filters={"minutes": 60},
                total_sessions_found=2,
                actual_sessions_returned=2,
                sessions=[],
            )
            mock_handler.search_enriched_active_sessions = AsyncMock(return_value=mock_return)

            from server import sessions_search_with_advanced_details

            result = await sessions_search_with_advanced_details(username="testUser", limit=2)

            mock_handler.search_enriched_active_sessions.assert_called_once()
            call_kwargs = mock_handler.search_enriched_active_sessions.call_args[1]
            assert call_kwargs["username"] == "testUser"
            assert call_kwargs["limit"] == 2
            # Tool returns the typed model so FastMCP advertises an outputSchema
            # and populates structuredContent (serialized via to_jsonable_python).
            assert isinstance(result, EnrichedSessionSearchResult)
            data = pydantic_core.to_jsonable_python(result)
            assert data["actual_sessions_returned"] == 2

    @pytest.mark.asyncio
    async def test_sessions_search_with_advanced_details_default_params(self):
        from models.session_models import EnrichedSessionSearchResult

        with patch("server.session_tool_handler") as mock_handler:
            mock_handler.search_enriched_active_sessions = AsyncMock(
                return_value=EnrichedSessionSearchResult(
                    total_sessions_found=0, actual_sessions_returned=0, sessions=[]
                )
            )

            from server import sessions_search_with_advanced_details

            await sessions_search_with_advanced_details()

            kw = mock_handler.search_enriched_active_sessions.call_args[1]
            assert kw["username"] is None
            assert kw["calling_station_id"] is None
            assert kw["minutes"] == 60
            assert kw["limit"] == 1


class TestGetSessionsWithPolicyContext:
    """Unit tests for sessions_search_with_policy_details MCP tool.

    The tool is a thin wrapper: it calls session_tool_handler.search_enriched_active_sessions
    then policy_context_resolver.enrich_sessions_with_policy_context.
    Orchestration logic (caching, missing policy names) is tested in
    test_policy_context_resolver.py.
    """

    @staticmethod
    def _make_enriched_result():
        from models.session_models import EnrichedSessionSearchResult
        return EnrichedSessionSearchResult(
            search_filters={"minutes": 60},
            total_sessions_found=2,
            actual_sessions_returned=0,
            sessions=[],
        )

    @staticmethod
    def _make_final_result():
        from models.session_models import PolicyEnrichedSessionSearchResult, SessionWithPolicyContext, SessionDetail
        from models.policy_models import PolicyContext, PolicySetSummary
        return PolicyEnrichedSessionSearchResult(
            search_filters={"minutes": 60},
            total_sessions_found=2,
            actual_sessions_returned=2,
            sessions=[
                SessionWithPolicyContext(
                    session=SessionDetail(user_name="testUser"),
                    policy_context=PolicyContext(policy_set=PolicySetSummary(name="P1")),
                ),
                SessionWithPolicyContext(
                    session=SessionDetail(user_name="iseAiUser"),
                    policy_context=PolicyContext(policy_set=PolicySetSummary(name="P1")),
                ),
            ],
        )

    @pytest.mark.asyncio
    async def test_delegates_to_handler_and_resolver(self):
        """Tool calls search_enriched then enrich_sessions_with_policy_context."""
        enriched = self._make_enriched_result()
        final = self._make_final_result()

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.policy_context_resolver") as mock_pcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(return_value=enriched)
            mock_pcr.enrich_sessions_with_policy_context = AsyncMock(return_value=final)

            from server import sessions_search_with_policy_details

            result = await sessions_search_with_policy_details()

            mock_sth.search_enriched_active_sessions.assert_called_once()
            mock_pcr.enrich_sessions_with_policy_context.assert_called_once_with(enriched)
            # This tool returns a dict (it projects out SessionDetail fields
            # already covered by the advanced-details view); FastMCP emits the
            # dict as structuredContent.
            assert isinstance(result, dict)
            assert result["total_sessions_found"] == 2
            assert len(result["sessions"]) == 2

    @pytest.mark.asyncio
    async def test_passes_filters_to_search_enriched(self):
        """Filter parameters are forwarded to search_enriched_active_sessions."""
        enriched = self._make_enriched_result()
        final = self._make_final_result()

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.policy_context_resolver") as mock_pcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(return_value=enriched)
            mock_pcr.enrich_sessions_with_policy_context = AsyncMock(return_value=final)

            from server import sessions_search_with_policy_details

            await sessions_search_with_policy_details(
                username="testUser", minutes=360, limit=2
            )

            call_kwargs = mock_sth.search_enriched_active_sessions.call_args[1]
            assert call_kwargs["username"] == "testUser"
            assert call_kwargs["minutes"] == 360
            assert call_kwargs["limit"] == 2

    @pytest.mark.asyncio
    async def test_default_params(self):
        enriched = self._make_enriched_result()
        final = self._make_final_result()

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.policy_context_resolver") as mock_pcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(return_value=enriched)
            mock_pcr.enrich_sessions_with_policy_context = AsyncMock(return_value=final)

            from server import sessions_search_with_policy_details

            await sessions_search_with_policy_details()

            kw = mock_sth.search_enriched_active_sessions.call_args[1]
            assert kw["username"] is None
            assert kw["calling_station_id"] is None
            assert kw["minutes"] == 60
            assert kw["limit"] == 1


class TestGetSessionsWithLatencyDetails:
    """Unit tests for sessions_search_with_latency_details MCP tool.

    The tool is a thin wrapper: it calls session_tool_handler.search_enriched_active_sessions
    then latency_context_resolver.enrich_sessions_with_latency_context.
    Resolver logic itself is tested separately.
    """

    @staticmethod
    def _make_enriched_result(**overrides):
        from models.session_models import EnrichedSessionSearchResult
        defaults = dict(
            search_filters={"minutes": 60},
            total_sessions_found=2,
            actual_sessions_returned=0,
            sessions=[],
        )
        defaults.update(overrides)
        return EnrichedSessionSearchResult(**defaults)

    @staticmethod
    def _make_final_result(**overrides):
        from models.session_models import (
            LatencyEnrichedSessionSearchResult,
            SessionWithLatencyContext,
            SessionDetail,
        )
        defaults = dict(
            search_filters={"minutes": 60},
            total_sessions_found=2,
            actual_sessions_returned=2,
            sessions=[
                SessionWithLatencyContext(
                    session=SessionDetail(user_name="testUser"),
                    execution_steps=None,
                    latency_context_note="No execution steps found in session data",
                ),
            ],
        )
        defaults.update(overrides)
        return LatencyEnrichedSessionSearchResult(**defaults)

    @pytest.mark.asyncio
    async def test_delegates_to_handler_and_resolver(self):
        """Tool calls search_enriched then enrich_sessions_with_latency_context."""
        enriched = self._make_enriched_result()
        final = self._make_final_result()

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.latency_context_resolver") as mock_lcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(return_value=enriched)
            mock_lcr.enrich_sessions_with_latency_context = Mock(return_value=final)

            from server import sessions_search_with_latency_details

            result = await sessions_search_with_latency_details()

            mock_sth.search_enriched_active_sessions.assert_called_once()
            mock_lcr.enrich_sessions_with_latency_context.assert_called_once_with(enriched)
            # Tool returns the typed model; FastMCP serializes it into
            # structuredContent via to_jsonable_python.
            from models.session_models import LatencyEnrichedSessionSearchResult
            assert isinstance(result, LatencyEnrichedSessionSearchResult)
            data = pydantic_core.to_jsonable_python(result)
            assert data["total_sessions_found"] == 2

    @pytest.mark.asyncio
    async def test_passes_filters_to_search_enriched(self):
        """All filter parameters are forwarded to search_enriched_active_sessions."""
        enriched = self._make_enriched_result()
        final = self._make_final_result()

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.latency_context_resolver") as mock_lcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(return_value=enriched)
            mock_lcr.enrich_sessions_with_latency_context = Mock(return_value=final)

            from server import sessions_search_with_latency_details

            await sessions_search_with_latency_details(
                username="alice",
                calling_station_id="AA:BB:CC:DD:EE:FF",
                min_latency_ms=100,
                max_latency_ms=5000,
                minutes=360,
                limit=2,
            )

            call_kwargs = mock_sth.search_enriched_active_sessions.call_args[1]
            assert call_kwargs["username"] == "alice"
            assert call_kwargs["calling_station_id"] == "AA:BB:CC:DD:EE:FF"
            assert call_kwargs["min_latency_ms"] == 100
            assert call_kwargs["max_latency_ms"] == 5000
            assert call_kwargs["minutes"] == 360
            assert call_kwargs["limit"] == 2

    @pytest.mark.asyncio
    async def test_default_params(self):
        """Default parameter values are forwarded correctly."""
        enriched = self._make_enriched_result()
        final = self._make_final_result()

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.latency_context_resolver") as mock_lcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(return_value=enriched)
            mock_lcr.enrich_sessions_with_latency_context = Mock(return_value=final)

            from server import sessions_search_with_latency_details

            await sessions_search_with_latency_details()

            kw = mock_sth.search_enriched_active_sessions.call_args[1]
            assert kw["username"] is None
            assert kw["calling_station_id"] is None
            assert kw["min_latency_ms"] is None
            assert kw["max_latency_ms"] is None
            assert kw["minutes"] == 60
            assert kw["limit"] == 1

    @pytest.mark.asyncio
    async def test_enriched_result_passed_to_resolver(self):
        """The exact object returned by the handler is forwarded to the resolver."""
        enriched = self._make_enriched_result(total_sessions_found=7)
        final = self._make_final_result(total_sessions_found=7)

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.latency_context_resolver") as mock_lcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(return_value=enriched)
            mock_lcr.enrich_sessions_with_latency_context = Mock(return_value=final)

            from server import sessions_search_with_latency_details

            result = await sessions_search_with_latency_details()

            passed_arg = mock_lcr.enrich_sessions_with_latency_context.call_args[0][0]
            assert passed_arg is enriched
            # Tool returns the resolver's typed result unchanged.
            assert result is final
            data = pydantic_core.to_jsonable_python(result)
            assert data["total_sessions_found"] == final.total_sessions_found

    @pytest.mark.asyncio
    async def test_returns_typed_model_for_structured_content(self):
        """The tool returns the typed model so FastMCP advertises an
        outputSchema and populates the MCP structuredContent channel, while
        still mirroring a JSON text block for legacy clients.
        """
        enriched = self._make_enriched_result()
        final = self._make_final_result()

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.latency_context_resolver") as mock_lcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(return_value=enriched)
            mock_lcr.enrich_sessions_with_latency_context = Mock(return_value=final)

            from server import sessions_search_with_latency_details

            result = await sessions_search_with_latency_details()

            from models.session_models import LatencyEnrichedSessionSearchResult
            assert isinstance(result, LatencyEnrichedSessionSearchResult)
            data = pydantic_core.to_jsonable_python(result)
            assert "sessions" in data
            assert "total_sessions_found" in data

    @pytest.mark.asyncio
    async def test_zero_sessions_still_calls_resolver(self):
        """When the handler returns zero sessions the resolver is still invoked."""
        enriched = self._make_enriched_result(
            total_sessions_found=0, actual_sessions_returned=0, sessions=[]
        )
        final = self._make_final_result(
            total_sessions_found=0, actual_sessions_returned=0, sessions=[]
        )

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.latency_context_resolver") as mock_lcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(return_value=enriched)
            mock_lcr.enrich_sessions_with_latency_context = Mock(return_value=final)

            from server import sessions_search_with_latency_details

            result = await sessions_search_with_latency_details()

            mock_lcr.enrich_sessions_with_latency_context.assert_called_once_with(enriched)
            data = pydantic_core.to_jsonable_python(result)
            assert data["total_sessions_found"] == 0
            assert data["actual_sessions_returned"] == 0
            assert data["sessions"] == []

    @pytest.mark.asyncio
    async def test_handler_error_propagates_without_calling_resolver(self):
        """If the handler raises, the error propagates and the resolver is never called."""
        from fastmcp.exceptions import ToolError as McpToolError

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.latency_context_resolver") as mock_lcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(
                side_effect=McpToolError("handler boom")
            )
            mock_lcr.enrich_sessions_with_latency_context = Mock()

            from server import sessions_search_with_latency_details

            with pytest.raises(McpToolError):
                await sessions_search_with_latency_details()

            mock_lcr.enrich_sessions_with_latency_context.assert_not_called()

    @pytest.mark.asyncio
    async def test_resolver_error_propagates(self):
        """If the resolver raises, the error propagates to the caller."""
        from fastmcp.exceptions import ToolError as McpToolError

        enriched = self._make_enriched_result()

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.latency_context_resolver") as mock_lcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(return_value=enriched)
            mock_lcr.enrich_sessions_with_latency_context = Mock(
                side_effect=McpToolError("resolver boom")
            )

            from server import sessions_search_with_latency_details

            with pytest.raises(McpToolError):
                await sessions_search_with_latency_details()

    @pytest.mark.asyncio
    async def test_only_min_latency_forwarded(self):
        """Supplying only min_latency_ms (no max) forwards correctly."""
        enriched = self._make_enriched_result()
        final = self._make_final_result()

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.latency_context_resolver") as mock_lcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(return_value=enriched)
            mock_lcr.enrich_sessions_with_latency_context = Mock(return_value=final)

            from server import sessions_search_with_latency_details

            await sessions_search_with_latency_details(min_latency_ms=200)

            kw = mock_sth.search_enriched_active_sessions.call_args[1]
            assert kw["min_latency_ms"] == 200
            assert kw["max_latency_ms"] is None

    @pytest.mark.asyncio
    async def test_only_max_latency_forwarded(self):
        """Supplying only max_latency_ms (no min) forwards correctly."""
        enriched = self._make_enriched_result()
        final = self._make_final_result()

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.latency_context_resolver") as mock_lcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(return_value=enriched)
            mock_lcr.enrich_sessions_with_latency_context = Mock(return_value=final)

            from server import sessions_search_with_latency_details

            await sessions_search_with_latency_details(max_latency_ms=1000)

            kw = mock_sth.search_enriched_active_sessions.call_args[1]
            assert kw["min_latency_ms"] is None
            assert kw["max_latency_ms"] == 1000

    @pytest.mark.asyncio
    async def test_response_fields_with_sessions_and_steps(self):
        """Validate response structure when sessions contain execution steps."""
        from models.session_models import (
            EnrichedSessionSearchResult,
            LatencyEnrichedSessionSearchResult,
            SessionWithLatencyContext,
            SessionDetail,
            ExecutionStep,
        )

        session_detail = SessionDetail(
            user_name="bob",
            calling_station_id="AA:BB:CC:DD:EE:FF",
            response_time=350,
        )
        enriched = EnrichedSessionSearchResult(
            search_filters={"minutes": 720, "min_latency_ms": 100},
            total_sessions_found=1,
            actual_sessions_returned=1,
            sessions=[session_detail],
        )
        final = LatencyEnrichedSessionSearchResult(
            search_filters={"minutes": 720, "min_latency_ms": 100},
            total_sessions_found=1,
            actual_sessions_returned=1,
            sessions=[
                SessionWithLatencyContext(
                    session=session_detail,
                    execution_steps=[
                        ExecutionStep(code="11001", text="Received RADIUS Access-Request", latency_ms=5),
                        ExecutionStep(code="11017", text="RADIUS created a new session", latency_ms=None),
                    ],
                    latency_context_note=None,
                ),
            ],
        )

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.latency_context_resolver") as mock_lcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(return_value=enriched)
            mock_lcr.enrich_sessions_with_latency_context = Mock(return_value=final)

            from server import sessions_search_with_latency_details

            result = await sessions_search_with_latency_details(
                username="bob", min_latency_ms=100, minutes=720
            )

            # The IseResultModel serializer drops None fields, so we assert
            # absence rather than equality with None.
            data = pydantic_core.to_jsonable_python(result)
            assert data["search_filters"] == {"minutes": 720, "min_latency_ms": 100}
            assert data["total_sessions_found"] == 1
            assert data["actual_sessions_returned"] == 1
            assert len(data["sessions"]) == 1

            session_ctx = data["sessions"][0]
            assert session_ctx["session"]["user_name"] == "bob"
            assert "latency_context_note" not in session_ctx
            assert len(session_ctx["execution_steps"]) == 2
            assert session_ctx["execution_steps"][0]["text"] == "Received RADIUS Access-Request"
            assert session_ctx["execution_steps"][0]["latency_ms"] == 5
            assert "latency_ms" not in session_ctx["execution_steps"][1]

    @pytest.mark.asyncio
    async def test_response_preserves_latency_context_note(self):
        """When the resolver sets latency_context_note, it appears in the result."""
        from models.session_models import (
            SessionWithLatencyContext,
            SessionDetail,
            ExecutionStep,
        )

        session_detail = SessionDetail(user_name="carol")
        final = self._make_final_result(
            total_sessions_found=1,
            actual_sessions_returned=1,
            sessions=[
                SessionWithLatencyContext(
                    session=session_detail,
                    execution_steps=[ExecutionStep(code="99999", text=None, latency_ms=None)],
                    latency_context_note="1 of 1 step code(s) could not be resolved from the message catalog",
                ),
            ],
        )
        enriched = self._make_enriched_result()

        with patch("server.session_tool_handler") as mock_sth, \
             patch("server.latency_context_resolver") as mock_lcr:
            mock_sth.search_enriched_active_sessions = AsyncMock(return_value=enriched)
            mock_lcr.enrich_sessions_with_latency_context = Mock(return_value=final)

            from server import sessions_search_with_latency_details

            result = await sessions_search_with_latency_details()

            data = pydantic_core.to_jsonable_python(result)
            note = data["sessions"][0].get("latency_context_note")
            assert note is not None
            assert "could not be resolved" in note


class TestConfiguration:
    """Tests for module-level configuration derived from environment variables."""

    def test_port_from_env(self):
        with patch.dict(os.environ, {"PORT": "8081"}):
            if "server" in sys.modules:
                del sys.modules["server"]

            import server

            assert server.PORT == 8081

    def test_host_default(self):
        with patch.dict(os.environ, {}, clear=True):
            if "server" in sys.modules:
                del sys.modules["server"]

            import server

            assert server.HOST == "0.0.0.0"


class TestDeploymentTool:
    """Unit tests for the ise_deployment_health MCP tool."""

    @pytest.mark.asyncio
    async def test_delegates_to_handler(self):
        import json
        from models.deployment_models import (
            DeploymentHealthResult,
            DeploymentHealthSummary,
            DeploymentNodeSummary,
        )

        node = DeploymentNodeSummary(
            hostname="vm218", fqdn="vm218.marcos.com", ip_address="10.127.96.218",
            roles=["PrimaryAdmin"], services=["Session"], node_status="Connected",
        )
        mock_return = DeploymentHealthResult(
            nodes=[node],
            summary=DeploymentHealthSummary.from_nodes([node]),
        )
        with patch("server.deployment_tool_handler") as mock_handler:
            mock_handler.get_deployment_health = AsyncMock(return_value=mock_return)
            from server import ise_deployment_health
            result = await ise_deployment_health(hostnames=["vm218"], diagnostics=True)

        mock_handler.get_deployment_health.assert_called_once()
        kw = mock_handler.get_deployment_health.call_args[1]
        assert kw["hostnames"] == ["vm218"]
        assert kw["diagnostics"] is True
        assert isinstance(result, DeploymentHealthResult)
        data = pydantic_core.to_jsonable_python(result)
        assert data["summary"]["verdict"] == "degraded"
        assert data["nodes"][0]["hostname"] == "vm218"

    @pytest.mark.asyncio
    async def test_default_params(self):
        from models.deployment_models import (
            DeploymentHealthResult,
            DeploymentHealthSummary,
        )
        mock_return = DeploymentHealthResult(
            nodes=[], summary=DeploymentHealthSummary.from_nodes([]),
        )
        with patch("server.deployment_tool_handler") as mock_handler:
            mock_handler.get_deployment_health = AsyncMock(return_value=mock_return)
            from server import ise_deployment_health
            await ise_deployment_health()

        kw = mock_handler.get_deployment_health.call_args[1]
        assert kw["hostnames"] is None
        assert kw["diagnostics"] is False


def test_diagnose_certificate_issues_registered():
    import server

    assert hasattr(server, "ise_diagnose_certificate_issues")


class TestDiagnoseCertificateIssuesTool:
    @pytest.mark.asyncio
    async def test_delegates_to_handler(self):
        import json
        from models.certificate_models import (
            CertExpirationSummary,
            CertLogScanResult,
            CertificateDiagnosisResult,
            ExpiringTrustedCertificatesResponse,
        )

        mock_return = CertificateDiagnosisResult(
            expiry=ExpiringTrustedCertificatesResponse(
                certificates=[],
                summary=CertExpirationSummary(
                    total_matched=0, expired_count=0, warning_count=0,
                    earliest_expiration=None, checked_at="2026-07-03T00:00:00+00:00",
                    expiry_window_days=30,
                ),
            ),
            log_scan=CertLogScanResult(
                nodes=[], psn_nodes_total=0, psn_nodes_scanned=0,
                psn_nodes_succeeded=0,
                coverage_note="Scanned 0 of 0 PSN node(s); 0 succeeded.",
            ),
            verdict="healthy",
            checked_at="2026-07-03T00:00:00+00:00",
        )
        with patch("server.certificates_tool_handler") as mock_handler:
            mock_handler.diagnose_certificate_issues = AsyncMock(return_value=mock_return)
            from server import ise_diagnose_certificate_issues
            result = await ise_diagnose_certificate_issues(
                expiry_days=15, status_filter="all", scan_logs=True, hostnames=["psn1"],
            )

        mock_handler.diagnose_certificate_issues.assert_called_once()
        kw = mock_handler.diagnose_certificate_issues.call_args[1]
        assert kw["expiry_days"] == 15
        assert kw["status_filter"] == "all"
        assert kw["scan_logs"] is True
        assert kw["hostnames"] == ["psn1"]
        assert isinstance(result, CertificateDiagnosisResult)
        assert pydantic_core.to_jsonable_python(result)["verdict"] == "healthy"

    @pytest.mark.asyncio
    async def test_default_params(self):
        from models.certificate_models import (
            CertExpirationSummary,
            CertificateDiagnosisResult,
            ExpiringTrustedCertificatesResponse,
        )
        mock_return = CertificateDiagnosisResult(
            expiry=ExpiringTrustedCertificatesResponse(
                certificates=[],
                summary=CertExpirationSummary(
                    total_matched=0, expired_count=0, warning_count=0,
                    earliest_expiration=None, checked_at="2026-07-03T00:00:00+00:00",
                    expiry_window_days=30,
                ),
            ),
            log_scan=None,
            verdict="healthy",
            checked_at="2026-07-03T00:00:00+00:00",
        )
        with patch("server.certificates_tool_handler") as mock_handler:
            mock_handler.diagnose_certificate_issues = AsyncMock(return_value=mock_return)
            from server import ise_diagnose_certificate_issues
            await ise_diagnose_certificate_issues()

        kw = mock_handler.diagnose_certificate_issues.call_args[1]
        assert kw["status_filter"] == "enabled"
        assert kw["scan_logs"] is True
        assert kw["hostnames"] is None
