# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

import sys
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

PROJECT_DIR = Path(__file__).resolve().parent.parent
if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

pytest_plugins = ("pytest_asyncio",)


def _raw_node(hostname, roles, status="Connected"):
    return {
        "hostname": hostname,
        "fqdn": f"{hostname}.marcos.com",
        "ipAddress": "10.127.96.218",
        "roles": roles,
        "services": ["Session"],
        "nodeStatus": status,
    }


def _make_handler():
    from tools.deployment_tool_handler import DeploymentToolHandler
    from services.deployment_diagnostics_resolver import DeploymentDiagnosticsResolver

    mock_factory = MagicMock()
    mock_factory.get_client.return_value = MagicMock()
    return DeploymentToolHandler(mock_factory, DeploymentDiagnosticsResolver())


class TestGetDeploymentHealth:
    @pytest.mark.asyncio
    async def test_all_nodes_no_filter(self):
        handler = _make_handler()
        raw = {"response": [
            _raw_node("vm218", ["PrimaryAdmin"]),
            _raw_node("vm219", ["SecondaryAdmin"]),
        ]}
        with patch.object(handler, "execute_api_call", new_callable=AsyncMock) as mock_exec:
            mock_exec.return_value = raw
            result = await handler.get_deployment_health()

        assert len(result.nodes) == 2
        assert result.summary.verdict == "healthy"
        assert result.diagnostics is None
        # No hostname filter passed
        kw = mock_exec.call_args[1]
        from autogenerated_api_clients.deployment.types import UNSET
        assert kw["filter_"] is UNSET

    @pytest.mark.asyncio
    async def test_single_hostname_builds_eq_filter(self):
        handler = _make_handler()
        with patch.object(handler, "execute_api_call", new_callable=AsyncMock) as mock_exec:
            mock_exec.return_value = {"response": [_raw_node("vm218", ["PrimaryAdmin"])]}
            await handler.get_deployment_health(hostnames=["vm218"])

        kw = mock_exec.call_args[1]
        assert kw["filter_"] == ["hostname.EQ.vm218"]
        from autogenerated_api_clients.deployment.types import UNSET
        # Single filter -> no OR filterType
        assert kw["filter_type"] is UNSET

    @pytest.mark.asyncio
    async def test_multiple_hostnames_use_or_filtertype(self):
        handler = _make_handler()
        with patch.object(handler, "execute_api_call", new_callable=AsyncMock) as mock_exec:
            mock_exec.return_value = {"response": []}
            await handler.get_deployment_health(hostnames=["vm218", "vm219"])

        kw = mock_exec.call_args[1]
        assert kw["filter_"] == ["hostname.EQ.vm218", "hostname.EQ.vm219"]
        from autogenerated_api_clients.deployment.models.get_deployment_nodes_filter_type import (
            GetDeploymentNodesFilterType,
        )
        assert kw["filter_type"] == GetDeploymentNodesFilterType.OR

    @pytest.mark.asyncio
    async def test_invalid_hostname_raises_before_api_call(self):
        from fastmcp.exceptions import ToolError
        handler = _make_handler()
        with patch.object(handler, "execute_api_call", new_callable=AsyncMock) as mock_exec:
            with pytest.raises(ToolError):
                await handler.get_deployment_health(hostnames=["bad.host.name"])
        mock_exec.assert_not_called()

    @pytest.mark.asyncio
    async def test_deep_diagnostics_attaches_diagnostics(self):
        from contextlib import asynccontextmanager
        handler = _make_handler()

        @asynccontextmanager
        async def _fetch(log_name, hostname):
            raise RuntimeError("no log in test")
            yield  # pragma: no cover

        with patch.object(handler, "execute_api_call", new_callable=AsyncMock) as mock_exec, \
             patch("services.deployment_diagnostics_resolver.log_service") as ls:
            ls.fetch = _fetch
            mock_exec.return_value = {"response": [
                _raw_node("vm220", [], status="NotInSync"),
            ]}
            result = await handler.get_deployment_health(deep_diagnostics=True)

        assert result.diagnostics is not None
        assert any("vm220" in o for o in result.diagnostics.observations)

    @pytest.mark.asyncio
    async def test_empty_response_yields_empty_nodes(self):
        handler = _make_handler()
        with patch.object(handler, "execute_api_call", new_callable=AsyncMock) as mock_exec:
            mock_exec.return_value = {"response": []}
            result = await handler.get_deployment_health()
        assert result.nodes == []
        assert result.summary.total_nodes == 0

    @pytest.mark.asyncio
    async def test_api_error_propagates(self):
        from fastmcp.exceptions import ToolError
        handler = _make_handler()
        with patch.object(handler, "execute_api_call", new_callable=AsyncMock) as mock_exec:
            mock_exec.side_effect = ToolError("boom")
            with pytest.raises(ToolError):
                await handler.get_deployment_health()

    @pytest.mark.asyncio
    async def test_filtered_summary_is_scoped(self):
        handler = _make_handler()
        with patch.object(handler, "execute_api_call", new_callable=AsyncMock) as mock_exec:
            mock_exec.return_value = {"response": [_raw_node("vm219", ["SecondaryAdmin"])]}
            result = await handler.get_deployment_health(hostnames=["vm219"])

        assert result.summary.scope == "filtered"
        assert result.summary.verdict == "healthy"
        assert result.summary.ha_ready is None
        assert result.summary.primary_admin_present is None

    @pytest.mark.asyncio
    async def test_unfiltered_summary_is_deployment_scope(self):
        handler = _make_handler()
        with patch.object(handler, "execute_api_call", new_callable=AsyncMock) as mock_exec:
            mock_exec.return_value = {"response": [
                _raw_node("vm218", ["PrimaryAdmin"]),
                _raw_node("vm219", ["SecondaryAdmin"]),
            ]}
            result = await handler.get_deployment_health()

        assert result.summary.scope == "deployment"
        assert result.summary.ha_ready is True

    @pytest.mark.asyncio
    async def test_filtered_nonexistent_hostname_reports_not_found(self):
        handler = _make_handler()
        with patch.object(handler, "execute_api_call", new_callable=AsyncMock) as mock_exec:
            mock_exec.return_value = {"response": []}
            result = await handler.get_deployment_health(hostnames=["ghost"])
        assert result.summary.scope == "filtered"
        assert result.summary.verdict == "critical"
        assert result.summary.not_found_hostnames == ["ghost"]
