# Copyright (c) 2025 Cisco Systems, Inc. All Rights Reserved

import base64
from dataclasses import dataclass
from enum import Enum
from typing import Dict, Optional, Type

import httpx

from autogenerated_api_clients.endpoints.client import (
    AuthenticatedClient as EndpointsClient,
)
from autogenerated_api_clients.certificates.client import (
    AuthenticatedClient as CertificatesClient,
)
from autogenerated_api_clients.policy.client import (
    AuthenticatedClient as PolicyClient,
)
from autogenerated_api_clients.patch_and_upgrade.client import (
    AuthenticatedClient as PatchAndUpgradeClient,
)
from autogenerated_api_clients.deployment.client import (
    AuthenticatedClient as DeploymentClient,
)

from clients.exceptions import (
    MissingIseCredentialError,
    MissingServiceAccountError,
)
from clients.request_context import get_per_user_credential
from clients.settings import settings
from clients.tls import build_ssl_context
from logger import logger


ISE_OPEN_API_BASE_PATH = "/api/v1"
ISE_PROTOCOL = "https"
ISE_AUTH_PREFIX = "Basic"


# ``MissingIseCredentialError`` and ``MissingServiceAccountError`` are
# defined once in ``clients.exceptions`` and re-exported here so that
# ``except`` clauses match the same class object regardless of whether
# the failure originated in the OpenAPI client path or in
# ``clients.mnt_client``. Keeping them importable from this module
# preserves the existing public surface.
__all__ = [
    "ClientFactory",
    "ClientName",
    "client_factory",
    "MissingIseCredentialError",
    "MissingServiceAccountError",
]


class ClientName(str, Enum):
    ENDPOINTS = "endpoints"
    CERTIFICATES = "certificates"
    POLICY = "policy"
    PATCH_AND_UPGRADE = "patch_and_upgrade"
    DEPLOYMENT = "deployment"


@dataclass(frozen=True)
class ClientRegistryEntry:
    client_class: Type
    base_path: str


class ClientFactory:
    """
    Factory for autogenerated ISE OpenAPI clients.

    The autogenerated ``AuthenticatedClient`` expects a pre-encoded
    ``token`` string and a ``prefix``; we keep that contract rather than
    forking generated code. Configuration (host, port, credentials,
    timeouts) is sourced from ``clients.settings.settings``. The shared
    SSL context (TLS 1.2+, peer verification disabled per design) comes
    from ``clients.tls.build_ssl_context``.
    """

    def __init__(self) -> None:
        self._clients: Dict[ClientName, object] = {}
        self._client_registry: Dict[ClientName, ClientRegistryEntry] = {
            ClientName.ENDPOINTS: ClientRegistryEntry(
                EndpointsClient, ISE_OPEN_API_BASE_PATH
            ),
            ClientName.CERTIFICATES: ClientRegistryEntry(CertificatesClient, ""),
            ClientName.POLICY: ClientRegistryEntry(
                PolicyClient, f"{ISE_OPEN_API_BASE_PATH}/policy"
            ),
            ClientName.PATCH_AND_UPGRADE: ClientRegistryEntry(
                PatchAndUpgradeClient, ISE_OPEN_API_BASE_PATH
            ),
            ClientName.DEPLOYMENT: ClientRegistryEntry(
                DeploymentClient, ISE_OPEN_API_BASE_PATH
            ),
        }

    def get_client(self, client_name: ClientName) -> object:
        """
        Return an AuthenticatedClient for the requested ISE API surface.

        Selection logic, in order:
        1. If the current request carried a per-user ISE credential
           header (NVA-forwarded ``X-ISE-Authorization``), build a
           fresh, *non-cached* client whose Authorization is set to
           that user's credential. We deliberately do NOT cache here:
           caching keyed by raw token risks (a) growing the cache
           unboundedly across users and (b) leaking one user's token
           to another if the cache key collides. The cost of building
           an httpx.AsyncClient per call is small compared to the LLM
           round trip that triggered it.
        2. Otherwise, if ``require_per_user_credential`` is true,
           raise -- we refuse to silently call ISE as the service
           account when policy says every action must be on behalf of
           the logged-in user.
        3. Otherwise, fall back to the cached service-account client
           (existing behaviour; preserves anonymous/dev/test paths).
        """
        per_user_credential = get_per_user_credential()
        if per_user_credential:
            return self._create_client(
                client_name, authorization_value=per_user_credential
            )
        # Cert mode: client cert configured -> standalone auth, no
        # Authorization header. Cached per ClientName like the SA path;
        # the cert is a single process-wide config, so there is no
        # per-user token to leak and no unbounded cache growth.
        if settings.client_cert_configured:
            if client_name not in self._clients:
                self._clients[client_name] = self._create_cert_mode_client(
                    client_name
                )
            return self._clients[client_name]
        if settings.require_per_user_credential:
            raise MissingIseCredentialError(
                "ISE_REQUIRE_PER_USER_CREDENTIAL=true but no "
                f"'{settings.credential_header_name}' header was "
                "forwarded with this request."
            )
        if client_name not in self._clients:
            self._clients[client_name] = self._create_client(client_name)
        return self._clients[client_name]

    def _create_client(
        self,
        client_name: ClientName,
        *,
        authorization_value: Optional[str] = None,
    ) -> object:
        """
        Construct an AuthenticatedClient.

        ``authorization_value`` is the pre-built ``Basic <b64...>``
        string forwarded by NVA via ``X-ISE-Authorization``. When
        provided, the openapi-generated client is configured with an
        empty prefix and the verbatim header value as the token so the
        Authorization header on every request becomes exactly the
        original NVA-captured value. When ``None`` we fall back to the
        legacy service-account credentials from settings.
        """
        if client_name not in self._client_registry:
            raise ValueError(f"Unknown client name: {client_name}")
        entry = self._client_registry[client_name]

        base_url = (
            f"{ISE_PROTOCOL}://{settings.ise_ip}:{settings.api_port}{entry.base_path}"
        )

        if authorization_value:
            # Per-user path. Split the value into prefix + token if it
            # looks like a standard `Basic <token>` so the
            # autogenerated client (which always emits
            # `Authorization: <prefix> <token>`) reconstructs the
            # exact original header. Anything that doesn't split
            # cleanly is sent verbatim with an empty prefix; this also
            # supports forwarding non-Basic schemes (e.g. Bearer) in
            # the future without code changes.
            parts = authorization_value.split(" ", 1)
            if len(parts) == 2:
                prefix, token = parts[0], parts[1]
            else:
                prefix, token = "", authorization_value
            logger.info(
                "Creating per-user ISE client",
                client_name=str(client_name),
                base_url=base_url,
                auth_prefix=prefix or "<empty>",
            )
        else:
            # Service-account fallback (legacy). Only reachable when
            # the inbound MCP request carried no X-ISE-Authorization
            # AND require_per_user_credential is False. We fail loud
            # here rather than silently emitting a malformed
            # Authorization header so the operator sees exactly what
            # is missing.
            if not settings.api_username or not settings.api_pwd:
                raise MissingServiceAccountError(
                    "Service-account fallback path was taken but "
                    "API_USERNAME / API_PWD are not configured in "
                    ".env. Either set them, or forward every MCP "
                    "request through NVA so the per-user header "
                    f"'{settings.credential_header_name}' is always "
                    "present, or set ISE_REQUIRE_PER_USER_CREDENTIAL=true "
                    "to refuse SA fallback explicitly."
                )
            creds = (
                f"{settings.api_username}:{settings.api_pwd.get_secret_value()}"
            )
            prefix = ISE_AUTH_PREFIX
            token = base64.b64encode(creds.encode("utf-8")).decode("ascii")
            logger.info(
                "Creating service-account ISE client",
                client_name=str(client_name),
                base_url=base_url,
            )

        timeout = httpx.Timeout(
            connect=settings.connect_timeout_s,
            read=settings.read_timeout_s,
            write=settings.write_timeout_s,
            pool=settings.pool_timeout_s,
        )

        return entry.client_class(
            base_url=base_url,
            prefix=prefix,
            token=token,
            verify_ssl=build_ssl_context(),
            timeout=timeout,
            follow_redirects=False,
        )

    def _create_cert_mode_client(self, client_name: ClientName) -> object:
        """Build a client that authenticates via client cert only.

        The autogenerated AuthenticatedClient always emits an
        ``Authorization`` header when it lazily builds its own httpx
        client. To send NO header (cert = standalone auth), we build the
        httpx clients ourselves and inject them via
        ``set_async_httpx_client`` / ``set_httpx_client``, which bypass
        that header-writing branch. ``token``/``prefix`` are placeholders
        that never reach the wire. The shared TLS context already carries
        the client cert (see clients/tls.py).
        """
        if client_name not in self._client_registry:
            raise ValueError(f"Unknown client name: {client_name}")
        entry = self._client_registry[client_name]

        base_url = (
            f"{ISE_PROTOCOL}://{settings.ise_ip}:{settings.api_port}{entry.base_path}"
        )
        timeout = httpx.Timeout(
            connect=settings.connect_timeout_s,
            read=settings.read_timeout_s,
            write=settings.write_timeout_s,
            pool=settings.pool_timeout_s,
        )
        ssl_context = build_ssl_context()

        logger.info(
            "Creating client-certificate ISE client (no Authorization header)",
            client_name=str(client_name),
            base_url=base_url,
        )

        client = entry.client_class(
            base_url=base_url,
            prefix="",
            token="",
            verify_ssl=ssl_context,
            timeout=timeout,
            follow_redirects=False,
        )
        async_httpx = httpx.AsyncClient(
            base_url=base_url,
            verify=ssl_context,
            timeout=timeout,
            follow_redirects=False,
        )
        sync_httpx = httpx.Client(
            base_url=base_url,
            verify=ssl_context,
            timeout=timeout,
            follow_redirects=False,
        )
        client.set_async_httpx_client(async_httpx)
        client.set_httpx_client(sync_httpx)
        return client

    def register_client_class(
        self, client_name: ClientName, client_class: Type, base_path: str
    ) -> None:
        self._client_registry[client_name] = ClientRegistryEntry(client_class, base_path)


client_factory = ClientFactory()
