# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# services/certificate_diagnostics_resolver.py
"""Scan ise-psc.log on PSN nodes for certificate/TLS error signals.

Discovers PSN nodes from the deployment node list, fetches each node's
``ise-psc.log`` via the log service (concurrently, capped), scans it with
``CertificateLogScanner``, and assembles a coverage-aware result. Per-node
failures are isolated and reported with a generic reason, mirroring
``DeploymentDiagnosticsResolver``.
"""

import asyncio
from typing import Optional

from autogenerated_api_clients.deployment.api.node_deployment import get_deployment_nodes

from clients.client_factory import ClientFactory, ClientName
from logger import logger
from models.certificate_models import CertLogMatch, CertLogNodeResult, CertLogScanResult
from models.deployment_models import DeploymentNodeSummary
from services.certificate_log_scanner import CertificateLogScanner
from services.log_service import log_service
from tools.base_tool_handler import BaseToolHandler

_LOG_NAME = "ise-psc"
_MAX_PSN_NODES = 5

PSN_SERVICES = {
    "Session",
    "Profiler",
    "TC-NAC",
    "SXP",
    "DeviceAdmin",
    "PassiveIdentity",
}


def is_psn(node: DeploymentNodeSummary) -> bool:
    """True when the node runs at least one PSN service."""
    return any(s in PSN_SERVICES for s in (node.services or []))


class CertificateDiagnosticsResolver(BaseToolHandler):
    def __init__(self, client_factory: ClientFactory):
        super().__init__(ClientName.DEPLOYMENT, client_factory)
        self._scanner = None

    @property
    def scanner(self) -> CertificateLogScanner:
        """Lazy initialization of scanner to support test mocking."""
        if self._scanner is None:
            self._scanner = CertificateLogScanner()
        return self._scanner

    async def _fetch_nodes(self) -> list[DeploymentNodeSummary]:
        raw_response = await self.execute_api_call(
            api_function=get_deployment_nodes.asyncio_detailed,
            operation_name="getDeploymentNodes",
        )
        response_list = (
            raw_response.get("response", []) if isinstance(raw_response, dict) else []
        )
        return [DeploymentNodeSummary.from_api(n) for n in response_list]

    def _select(
        self, nodes: list[DeploymentNodeSummary], hostnames: Optional[list[str]]
    ) -> list[DeploymentNodeSummary]:
        psns = [n for n in nodes if is_psn(n)]
        if hostnames:
            requested = set(hostnames)
            # A requested host that is not a PSN is silently skipped.
            psns = [n for n in psns if n.hostname in requested or n.fqdn in requested]
        return psns

    async def _scan_node(self, node: DeploymentNodeSummary) -> CertLogNodeResult:
        target = node.fqdn or node.hostname
        try:
            async with log_service.fetch(_LOG_NAME, target) as path:
                parsed = self.scanner.scan(path)
        except Exception as exc:  # auth / HTTP / zip / parse — isolate per node
            logger.info(
                "Cert diagnostics: ise-psc.log unavailable for node",
                hostname=node.hostname,
                error=str(exc),
            )
            return CertLogNodeResult(
                hostname=node.hostname,
                status="unavailable",
                reason="ise-psc.log could not be fetched; no certificate log "
                "signals available for this node",
            )

        if not parsed:
            return CertLogNodeResult(
                hostname=node.hostname, status="ok", matches=[], total_matches=0
            )
        return CertLogNodeResult(
            hostname=node.hostname,
            status="ok",
            matches=[CertLogMatch(line=ln) for ln in parsed["matches"]],
            total_matches=parsed["total_matches"],
        )

    async def resolve(
        self, hostnames: Optional[list[str]] = None
    ) -> CertLogScanResult:
        """Scan PSN ise-psc.log for certificate/TLS signals.

        Args:
            hostnames: When provided, restrict scanning to these nodes; any
                requested host that is not a PSN is silently skipped. When
                omitted, all PSN nodes are candidates (capped).
        """
        all_nodes = await self._fetch_nodes()
        candidates = self._select(all_nodes, hostnames)
        selected = candidates[:_MAX_PSN_NODES]

        results: list[CertLogNodeResult] = []
        if selected:
            results = list(
                await asyncio.gather(*(self._scan_node(n) for n in selected))
            )

        succeeded = sum(1 for r in results if r.status == "ok")
        coverage = (
            f"Scanned {succeeded} of {len(selected)} PSN node(s) successfully."
            if len(selected) == len(candidates)
            else f"Scanned {len(selected)} of {len(candidates)} PSN node(s); "
            f"{succeeded} of {len(selected)} succeeded."
        )
        logger.info(
            "Certificate log scan complete",
            psn_total=len(candidates),
            scanned=len(selected),
            succeeded=succeeded,
        )
        return CertLogScanResult(
            nodes=results,
            psn_nodes_total=len(candidates),
            psn_nodes_scanned=len(selected),
            psn_nodes_succeeded=succeeded,
            coverage_note=coverage,
        )
