#!/bin/bash

# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0


line_separator="--------------------------------"


echo -e "$line_separator"

echo -e "Generating endpoints API client..."
openapi-python-client generate \
  --path api_specs/endpoint-bundled.yaml \
  --config api_client_config/endpoints.yaml \
  --output-path ./autogenerated_api_clients/ \
  --overwrite
  echo -e "Finished generating endpoints API client!\n$line_separator"

# echo "Generating certificates API client..."
# openapi-python-client generate \
#   --path api_specs/certificates.json \
#   --config api_client_config/certificates.yaml \
#   --output-path ./autogenerated_api_clients/ \
#   --overwrite
#   echo -e "Finished generating certificates API client!\n$line_separator"

# echo "Generating Patch and Upgrade API client..."
# openapi-python-client generate \
#   --path api_specs/patch_and_upgrade.json \
#   --config api_client_config/patch_and_upgrade.yaml \
#   --output-path ./autogenerated_api_clients/ \
#   --overwrite
#   echo -e "Finished generating Patch and Upgrade API client!\n$line_separator"

echo "Generating Policy API client..."
openapi-python-client generate \
  --path api_specs/policy-bundled.yaml \
  --config api_client_config/policy.yaml \
  --output-path ./autogenerated_api_clients/ \
  --overwrite
  echo -e "Finished generating Policy API client!\n$line_separator"

echo "Client generation complete!"