# Copyright (c) 2025 Cisco Systems, Inc. All Rights Reserved

import re
from datetime import datetime, timezone, timedelta
from typing import Literal

from autogenerated_api_clients.certificates.api.certificates import get_trusted_certificates
from autogenerated_api_clients.certificates.models.get_trusted_certificates_sort import GetTrustedCertificatesSort
from autogenerated_api_clients.certificates.models.trust_certificate_response import TrustCertificateResponse

from clients.client_factory import ClientFactory, ClientName
from logger import logger
from models.certificate_models import (
    CertExpirationSummary,
    CertLogScanResult,
    CertificateDiagnosisResult,
    ExpiringCertificateSummary,
    ExpiringTrustedCertificatesResponse,
)
from services.certificate_diagnostics_resolver import CertificateDiagnosticsResolver
from tools.base_tool_handler import BaseToolHandler
from utils.certificate_validators import validate_cert_limit, validate_cert_status_filter, validate_expiry_days

# ISE filter API expects "yyyy-MM-dd HH:mm:ss"
_ISE_FILTER_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"

# ISE API response dates use Java's default toString():
#   "EEE MMM dd HH:mm:ss zzz yyyy" e.g. "Thu Apr 30 13:48:25 IDT 2026"
# The timezone abbreviation (IST, IDT, PST …) is ambiguous and non-standard,
# so we strip it and treat the remaining time as UTC for consistency.
_ISE_RESPONSE_DATE_FORMAT = "%a %b %d %H:%M:%S %Y"

_TZ_ABBREV_RE = re.compile(r"\s[A-Z]{2,5}\s(?=\d{4})")

# Page size sent to ISE per request — max supported by ISE API
_ISE_PAGE_SIZE = 100

# Maximum pages fetched per tool call to bound latency
_MAX_PAGES = 3

def _parse_ise_date(raw: str) -> datetime:
    """Parse an ISE date string to a timezone-aware UTC datetime.

    ISE response dates come in Java-style format:
        "Thu Apr 30 13:48:25 IDT 2026"
    The timezone abbreviation is ambiguous, so we strip it and treat as UTC.
    Also supports the filter-style format "yyyy-MM-dd HH:mm:ss" for backward
    compatibility with tests and any endpoint that might use it.
    """
    cleaned = raw.strip()
    try:
        dt = datetime.strptime(cleaned, _ISE_FILTER_DATE_FORMAT)
        return dt.replace(tzinfo=timezone.utc)
    except (ValueError, AttributeError):
        pass

    try:
        without_tz = _TZ_ABBREV_RE.sub(" ", cleaned)
        dt = datetime.strptime(without_tz.strip(), _ISE_RESPONSE_DATE_FORMAT)
        return dt.replace(tzinfo=timezone.utc)
    except (ValueError, AttributeError) as exc:
        raise ValueError(f"Cannot parse ISE date '{raw}': {exc}") from exc


def _format_ise_date(dt: datetime) -> str:
    """Format a datetime as an ISE filter-compatible date string."""
    return dt.strftime(_ISE_FILTER_DATE_FORMAT)


def _classify_expiry_status(days: int) -> Literal["expired", "warning"]:
    if days < 0:
        return "expired"
    return "warning"


def _build_cert_summary(
    cert: TrustCertificateResponse,
    now: datetime,
) -> ExpiringCertificateSummary | None:
    """Convert a raw ISE TrustCertificateResponse into an ExpiringCertificateSummary.

    Returns None when required fields are missing or the date cannot be parsed.
    """
    raw_expiry = cert.expiration_date
    raw_valid_from = cert.valid_from

    if not raw_expiry:
        logger.warning("Skipping certificate with missing expiration_date", cert_id=cert.id)
        return None

    try:
        expiry_dt = _parse_ise_date(raw_expiry)
    except ValueError:
        logger.warning("Skipping certificate with unparseable expiration_date", cert_id=cert.id, raw=raw_expiry)
        return None

    days_until_expiry = (expiry_dt - now).days

    valid_from_iso = ""
    if raw_valid_from:
        try:
            valid_from_iso = _parse_ise_date(raw_valid_from).isoformat()
        except ValueError:
            valid_from_iso = raw_valid_from

    return ExpiringCertificateSummary(
        friendly_name=cert.friendly_name or "",
        expiration_date=expiry_dt.isoformat(),
        valid_from=valid_from_iso,
        days_until_expiry=days_until_expiry,
        expiry_status=_classify_expiry_status(days_until_expiry),
        ise_status=cert.status or "",
        trusted_for=cert.trusted_for or "",
        is_referred_in_policy=bool(cert.additional_properties.get("isReferredInPolicy", False)),
    )


def _derive_verdict(
    expiry_summary: CertExpirationSummary,
    log_scan: CertLogScanResult | None,
) -> Literal["healthy", "warning", "critical"]:
    """Combine expiry counts and log signals into a single verdict.

    critical: any expired cert OR any matched log signal on any node.
    warning:  certs expiring within the window (none expired) and no signals.
    healthy:  nothing expiring/expired and no signals.
    """
    log_hits = 0
    if log_scan is not None:
        log_hits = sum(n.total_matches for n in log_scan.nodes)

    if expiry_summary.expired_count > 0 or log_hits > 0:
        return "critical"
    if expiry_summary.warning_count > 0:
        return "warning"
    return "healthy"


class CertificatesToolHandler(BaseToolHandler):
    """Handler for certificates-related MCP tools."""

    def __init__(
        self,
        client_factory: ClientFactory,
        diagnostics_resolver: CertificateDiagnosticsResolver,
    ):
        super().__init__(ClientName.CERTIFICATES, client_factory)
        self.diagnostics_resolver = diagnostics_resolver

    async def check_expiring_trusted_certificates(
        self,
        expiry_days: int = 30,
        include_expired: bool = True,
        status_filter: str = "enabled",
        limit: int = 25,
    ) -> ExpiringTrustedCertificatesResponse:
        """Fetch trusted certificates expiring within *expiry_days* and classify their expiry status.

        Args:
            expiry_days: Look-ahead window in days. Certs expiring within this window are returned.
            include_expired: When False, already-expired certificates are excluded from results.
            status_filter: One of 'all', 'enabled', 'disabled'. Filters on the ISE cert status field.
            limit: Maximum number of certificates to include in the response.

        Returns:
            ExpiringTrustedCertificatesResponse with sorted, classified certificates and aggregate summary.
        """
        validated_days = validate_expiry_days(expiry_days)
        validated_limit = validate_cert_limit(limit)
        validated_status: Literal["all", "enabled", "disabled"] = validate_cert_status_filter(status_filter)

        now = datetime.now(tz=timezone.utc)
        cutoff = now + timedelta(days=validated_days)
        cutoff_str = _format_ise_date(cutoff)

        # Server-side filter: expirationDate.LT.<cutoff> retrieves only certs expiring before window end.
        # ISE will include already-expired certs in this result set (their expiry < cutoff too).
        filter_param = f"expirationDate.LT.{cutoff_str}"

        logger.info(
            "Fetching expiring trusted certificates",
            expiry_days=validated_days,
            cutoff=cutoff_str,
            status_filter=validated_status,
            limit=validated_limit,
        )

        all_certs: list[ExpiringCertificateSummary] = []
        page = 1
        pages_fetched = 0

        while pages_fetched < _MAX_PAGES:
            raw_response = await self.execute_api_call(
                api_function=get_trusted_certificates.asyncio_detailed,
                operation_name="getTrustedCertificates",
                page=page,
                size=_ISE_PAGE_SIZE,
                sort=GetTrustedCertificatesSort.ASC,
                sort_by="expirationDate",
                filter_=filter_param,
            )
            pages_fetched += 1

            response_list = raw_response.get("response", []) if isinstance(raw_response, dict) else []
            if not response_list:
                break

            # Results are sorted ascending by expirationDate, so we can stop
            # processing the current page (and skip subsequent pages) as soon
            # as we have collected enough matching certs to satisfy the limit.
            limit_reached = False
            for raw_cert_dict in response_list:
                cert = TrustCertificateResponse.from_dict(raw_cert_dict)

                # Apply status filter client-side (ISE filter only supports EQ on status)
                if validated_status != "all":
                    cert_status = (cert.status or "").lower()
                    if cert_status != validated_status:
                        continue

                summary = _build_cert_summary(cert, now)
                if summary is None:
                    continue

                if not include_expired and summary.expiry_status == "expired":
                    continue

                all_certs.append(summary)

                if len(all_certs) >= validated_limit:
                    limit_reached = True
                    break

            if limit_reached:
                break

            # Check if there is a next page via ISE's pagination links
            next_page_link = raw_response.get("nextPage") if isinstance(raw_response, dict) else None
            if not next_page_link:
                break
            page += 1

        total_matched = len(all_certs)
        returned_certs = all_certs[:validated_limit]

        expired_count = sum(1 for c in returned_certs if c.expiry_status == "expired")
        warning_count = sum(1 for c in returned_certs if c.expiry_status == "warning")

        earliest_expiration: str | None = None
        if returned_certs:
            earliest_expiration = returned_certs[0].expiration_date

        logger.info(
            "Expiring trusted certificates check complete",
            total_matched=total_matched,
            returned=len(returned_certs),
            expired=expired_count,
            warning=warning_count,
        )

        return ExpiringTrustedCertificatesResponse(
            certificates=returned_certs,
            summary=CertExpirationSummary(
                total_matched=total_matched,
                expired_count=expired_count,
                warning_count=warning_count,
                earliest_expiration=earliest_expiration,
                checked_at=now.isoformat(),
                expiry_window_days=validated_days,
            ),
        )

    async def diagnose_certificate_issues(
        self,
        expiry_days: int = 30,
        status_filter: str = "enabled",
        scan_logs: bool = True,
        hostnames: list[str] | None = None,
        limit: int = 25,
    ) -> CertificateDiagnosisResult:
        """Diagnose certificate health: expiry check plus optional PSN log scan.

        Args:
            expiry_days: Look-ahead window for the trusted-cert expiry check.
            status_filter: 'all' | 'enabled' | 'disabled' (default 'enabled').
            scan_logs: When False, skip the PSN ise-psc.log scan entirely.
            hostnames: Restrict the log scan to these nodes (non-PSN hosts are
                silently skipped). Ignored by the expiry check.
            limit: Max certificates in the expiry result.

        Returns:
            CertificateDiagnosisResult with expiry, optional log_scan, and verdict.
        """
        expiry = await self.check_expiring_trusted_certificates(
            expiry_days=expiry_days,
            include_expired=True,
            status_filter=status_filter,
            limit=limit,
        )

        log_scan: CertLogScanResult | None = None
        if scan_logs:
            try:
                log_scan = await self.diagnostics_resolver.resolve(hostnames=hostnames)
            except Exception as exc:
                # Scan-wide failure (e.g. node discovery unavailable) must not sink
                # the already-successful expiry result. Degrade to an empty scan with
                # a generic coverage note; the error detail goes only to the log.
                logger.warning(
                    "Certificate log scan unavailable; returning expiry-only diagnosis",
                    error=str(exc),
                )
                log_scan = CertLogScanResult(
                    nodes=[],
                    psn_nodes_total=0,
                    psn_nodes_scanned=0,
                    psn_nodes_succeeded=0,
                    coverage_note="PSN log scan unavailable; certificate log signals "
                    "could not be collected. Verdict reflects the expiry check only.",
                )

        verdict = _derive_verdict(expiry.summary, log_scan)
        return CertificateDiagnosisResult(
            expiry=expiry,
            log_scan=log_scan,
            verdict=verdict,
            checked_at=datetime.now(tz=timezone.utc).isoformat(),
        )
