# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

from autogenerated_api_clients.deployment.api.node_deployment import get_deployment_nodes
from autogenerated_api_clients.deployment.models.get_deployment_nodes_filter_type import (
    GetDeploymentNodesFilterType,
)
from autogenerated_api_clients.deployment.types import UNSET

from clients.client_factory import ClientFactory, ClientName
from logger import logger
from models.deployment_models import (
    DeploymentHealthResult,
    DeploymentHealthSummary,
    DeploymentNodeSummary,
)
from services.deployment_diagnostics_resolver import DeploymentDiagnosticsResolver
from tools.base_tool_handler import BaseToolHandler
from utils.input_validators import validate_hostname


class DeploymentToolHandler(BaseToolHandler):
    """Handler for the ISE deployment-health MCP tool."""

    def __init__(
        self,
        client_factory: ClientFactory,
        diagnostics_resolver: DeploymentDiagnosticsResolver,
    ):
        super().__init__(ClientName.DEPLOYMENT, client_factory)
        self.diagnostics_resolver = diagnostics_resolver

    async def get_deployment_health(
        self,
        hostnames: list[str] | None = None,
        deep_diagnostics: bool = False,
    ) -> DeploymentHealthResult:
        """Fetch deployed nodes and compute a derived health assessment.

        Args:
            hostnames: Exact node hostnames to filter on (OR-combined).
                None/empty returns all nodes.
            deep_diagnostics: When True, attach deeper diagnostics via the
                DeploymentDiagnosticsResolver.

        Returns:
            DeploymentHealthResult with nodes, summary, and optional diagnostics.
        """
        filter_param = UNSET
        filter_type = UNSET
        if hostnames:
            validated = [validate_hostname(h) for h in hostnames]
            filter_param = [f"hostname.EQ.{h}" for h in validated]
            if len(filter_param) > 1:
                filter_type = GetDeploymentNodesFilterType.OR

        logger.info(
            "Fetching deployment nodes",
            hostname_count=len(hostnames) if hostnames else 0,
            deep_diagnostics=deep_diagnostics,
        )

        raw_response = await self.execute_api_call(
            api_function=get_deployment_nodes.asyncio_detailed,
            operation_name="getDeploymentNodes",
            filter_=filter_param,
            filter_type=filter_type,
        )

        response_list = (
            raw_response.get("response", []) if isinstance(raw_response, dict) else []
        )
        nodes = [DeploymentNodeSummary.from_api(n) for n in response_list]
        summary = DeploymentHealthSummary.from_nodes(
            nodes, requested_hostnames=hostnames
        )

        diagnostics = None
        if deep_diagnostics:
            diagnostics = await self.diagnostics_resolver.resolve(
                nodes, scoped=bool(hostnames)
            )

        logger.info(
            "Deployment health computed",
            total_nodes=summary.total_nodes,
            verdict=summary.verdict,
            unhealthy=len(summary.unhealthy_nodes),
        )

        return DeploymentHealthResult(
            nodes=nodes, summary=summary, diagnostics=diagnostics
        )
