# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

from typing import Any

from tools.base_tool_handler import BaseToolHandler
from clients.client_factory import ClientFactory, ClientName
from autogenerated_api_clients.endpoints.api.endpoints import get_rejected_endpoints


class EndpointsToolHandler(BaseToolHandler):
    """Handler for endpoint-related tools"""

    def __init__(self, client_factory: ClientFactory):
        super().__init__(ClientName.ENDPOINTS, client_factory)

    async def get_rejected_endpoints(self) -> list[dict[str, Any]]:
        response = await self.execute_api_call(api_function=get_rejected_endpoints.asyncio_detailed, operation_name="getRejectedEndpoints")
        return response.get("response", [])

