# Copyright (c) 2025 Cisco Systems, Inc. All Rights Reserved

import asyncio
from typing import Any, Optional, List, Dict

from logger import logger
from models.error_models import ErrorCategory, raise_tool_error
from models.policy_models import (
    AuthenticationRuleHit,
    AuthenticationRuleSearchResult,
    AuthenticationRuleSummary,
    AuthenticationRulesSection,
    AuthorizationProfileSearchResult,
    AuthorizationProfileSummary,
    AuthorizationRuleHit,
    AuthorizationRuleSearchResult,
    AuthorizationRuleSummary,
    AuthorizationRulesSection,
    IdentityStoreSummary,
    IdentityStoresSection,
    LibraryConditionSearchResult,
    LibraryConditionSummary,
    LocalExceptionRulesSection,
    PolicyAuthoringReferencesResult,
    PolicySetDetailsResult,
    PolicySetSearchResult,
    PolicySetSummary,
    SecurityGroupSummary,
    SecurityGroupsSection,
    ServiceNameSummary,
    ServiceNamesSection,
)
from utils.policy_condition_summary import condition_to_summary
from tools.base_tool_handler import BaseToolHandler
from clients.client_factory import ClientFactory, ClientName
from utils.input_validators import (
    validate_condition_scope_filter,
    validate_hit_counts_range,
    validate_limit,
    validate_max_hit_counts,
    validate_min_hit_counts,
    validate_name_substring,
    validate_policy_set_name,
    validate_policy_set_state_filter,
    validate_rule_state_filter,
)

from autogenerated_api_clients.policy.api.network_access_policy_sets import (
    get_network_access_policy_set_list,
    get_network_access_policy_set_by_id,
)
from autogenerated_api_clients.policy.api.network_access_authentication_rules import (
    get_network_access_policy_by_id_authentication_rule_list,
)
from autogenerated_api_clients.policy.api.network_access_authorization_rules import (
    get_network_access_policy_by_id_authorization_rule_list,
)
from autogenerated_api_clients.policy.api.network_access_authorization_exception_rules import (
    get_network_access_policy_by_id_local_exception_rule_list,
)
from autogenerated_api_clients.policy.api.network_access_authorization_global_exception_rules import (
    get_network_access_policy_set_global_exception_rule_list,
)
from autogenerated_api_clients.policy.api.network_access_authorization_profiles import (
    get_network_access_profiles,
)
from autogenerated_api_clients.policy.api.network_access_conditions import (
    get_network_access_conditions,
    get_network_access_conditions_for_policy_set,
    get_network_access_conditions_for_authentication_rule,
    get_network_access_conditions_for_authorization_rule,
)
from autogenerated_api_clients.policy.api.network_access_identity_stores import (
    get_network_access_identity_stores,
)
from autogenerated_api_clients.policy.api.network_access_security_groups import (
    get_network_access_security_groups,
)
from autogenerated_api_clients.policy.api.network_access_service_names import (
    get_network_access_service_names,
)


# Hard cap on the number of policy sets scanned during a fan-out search
# (Tools 3 and 4) when no specific policy_set_name was provided. Bounds
# tail latency at the cost of completeness; the SLM is informed via
# `policy_sets_scanned` in the result envelope.
_MAX_FAN_OUT_POLICY_SETS = 25


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _normalize_state(value: Any) -> Optional[str]:
    """Normalize the ISE state field to a canonical lowercase string.

    ISE returns either a string or an enum-shaped value depending on the
    code path. Returns None when the value is missing or not coercible.
    """
    if value is None:
        return None
    if isinstance(value, str):
        return value.strip().lower() or None
    return str(value).strip().lower() or None


def _state_filter_matches(rule_state: Optional[str], filter_value: str) -> bool:
    if filter_value == "all":
        return True
    return rule_state == filter_value


def _name_matches(name: Optional[str], substring: Optional[str]) -> bool:
    if substring is None:
        return True
    if not name:
        return False
    return substring.lower() in name.lower()


def _profile_list_matches(profile_value: Any, substring: Optional[str]) -> bool:
    """Case-insensitive substring match against any profile name in a list."""
    if substring is None:
        return True
    if not profile_value:
        return False
    needle = substring.lower()
    if isinstance(profile_value, list):
        return any(isinstance(p, str) and needle in p.lower() for p in profile_value)
    if isinstance(profile_value, str):
        return needle in profile_value.lower()
    return False


def _security_group_matches(value: Any, substring: Optional[str]) -> bool:
    if substring is None:
        return True
    if not value:
        return False
    if isinstance(value, str):
        return substring.lower() in value.lower()
    return False


def _identity_source_matches(value: Any, substring: Optional[str]) -> bool:
    if substring is None:
        return True
    if not value:
        return False
    if isinstance(value, str):
        return substring.lower() in value.lower()
    return False


def _build_authn_rule_summary(entry: Dict[str, Any]) -> AuthenticationRuleSummary:
    rule = entry.get("rule") or {}
    return AuthenticationRuleSummary(
        name=rule.get("name") or "",
        rank=rule.get("rank"),
        state=_normalize_state(rule.get("state")),
        hit_counts=rule.get("hitCounts"),
        identity_source_name=entry.get("identitySourceName"),
        if_auth_fail=entry.get("ifAuthFail"),
        if_user_not_found=entry.get("ifUserNotFound"),
        if_process_fail=entry.get("ifProcessFail"),
        condition_summary=condition_to_summary(rule.get("condition")),
    )


def _build_authz_rule_summary(entry: Dict[str, Any]) -> AuthorizationRuleSummary:
    rule = entry.get("rule") or {}
    return AuthorizationRuleSummary(
        name=rule.get("name") or "",
        rank=rule.get("rank"),
        state=_normalize_state(rule.get("state")),
        hit_counts=rule.get("hitCounts"),
        profile=entry.get("profile"),
        security_group=entry.get("securityGroup"),
        condition_summary=condition_to_summary(rule.get("condition")),
    )


def _build_policy_set_summary(raw: Dict[str, Any]) -> PolicySetSummary:
    return PolicySetSummary(
        name=raw.get("name") or "",
        description=raw.get("description"),
        state=_normalize_state(raw.get("state")),
        rank=raw.get("rank"),
        hit_counts=raw.get("hitCounts"),
        is_default=raw.get("default"),
        service_name=raw.get("serviceName"),
        is_proxy=raw.get("isProxy"),
        condition_summary=condition_to_summary(raw.get("condition")),
    )


def _sort_by_rank(entries: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Sort rule list entries by ``rule.rank`` ascending. Stable for missing ranks."""
    def key(e: Dict[str, Any]) -> int:
        rule = e.get("rule") or {}
        rank = rule.get("rank")
        return rank if isinstance(rank, int) else 1_000_000
    return sorted(entries, key=key)


def _sort_policy_sets_by_rank(items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    def key(p: Dict[str, Any]) -> int:
        rank = p.get("rank")
        return rank if isinstance(rank, int) else 1_000_000
    return sorted(items, key=key)


# ===========================================================================
# Handler
# ===========================================================================

class PolicyToolHandler(BaseToolHandler):
    """Handler for Cisco ISE Policy MCP tools.

    All read operations against the ISE Network Access Policy API. Names are
    the only identifier exposed to callers (and to the SLM); UUIDs returned
    by ISE upstream APIs are used internally to build path parameters and
    are dropped before serialization.
    """

    def __init__(self, client_factory: ClientFactory):
        super().__init__(ClientName.POLICY, client_factory)

    # -----------------------------------------------------------------
    # Lower-level wrappers used by both the new tools and the existing
    # session-driven PolicyContextResolver.
    # -----------------------------------------------------------------

    async def get_network_access_policy_set_list(self) -> list[dict[str, Any]]:
        response = await self.execute_api_call(
            api_function=get_network_access_policy_set_list.asyncio_detailed,
            operation_name="get_network_access_policy_set_list",
        )
        return response.get("response", []) if isinstance(response, dict) else []

    async def get_network_access_policy_set_by_id(self, policy_id: str) -> Dict[str, Any]:
        response = await self.execute_api_call(
            api_function=get_network_access_policy_set_by_id.asyncio_detailed,
            operation_name="get_network_access_policy_set_by_id",
            policy_id=policy_id,
        )
        if isinstance(response, dict):
            return response.get("response", response) or {}
        return {}

    async def get_network_access_authentication_rule_list(self, policy_id: str) -> list[dict[str, Any]]:
        response = await self.execute_api_call(
            api_function=get_network_access_policy_by_id_authentication_rule_list.asyncio_detailed,
            operation_name="get_network_access_authentication_rule_list",
            policy_id=policy_id,
        )
        return response.get("response", []) if isinstance(response, dict) else []

    async def get_network_access_authorization_rule_list(self, policy_id: str) -> list[dict[str, Any]]:
        response = await self.execute_api_call(
            api_function=get_network_access_policy_by_id_authorization_rule_list.asyncio_detailed,
            operation_name="get_network_access_authorization_rule_list",
            policy_id=policy_id,
        )
        return response.get("response", []) if isinstance(response, dict) else []

    async def get_network_access_local_exception_rule_list(self, policy_id: str) -> list[dict[str, Any]]:
        response = await self.execute_api_call(
            api_function=get_network_access_policy_by_id_local_exception_rule_list.asyncio_detailed,
            operation_name="get_network_access_local_exception_rule_list",
            policy_id=policy_id,
        )
        return response.get("response", []) if isinstance(response, dict) else []

    async def get_network_access_global_exception_rule_list(self) -> list[dict[str, Any]]:
        response = await self.execute_api_call(
            api_function=get_network_access_policy_set_global_exception_rule_list.asyncio_detailed,
            operation_name="get_network_access_global_exception_rule_list",
        )
        return response.get("response", []) if isinstance(response, dict) else []

    async def get_network_access_authorization_profiles(self) -> list[dict[str, Any]]:
        response = await self.execute_api_call(
            api_function=get_network_access_profiles.asyncio_detailed,
            operation_name="get_network_access_authorization_profiles",
        )
        # The endpoint returns a JSON array directly (not wrapped under "response").
        if isinstance(response, list):
            return response
        if isinstance(response, dict):
            return response.get("response", []) or []
        return []

    async def get_network_access_library_conditions(self, scope: str) -> list[dict[str, Any]]:
        """Fetch library conditions for the requested scope.

        ``scope`` must be one of ``"all"``, ``"policyset"``, ``"authentication"``,
        ``"authorization"`` (already validated by the caller).
        """
        api_map = {
            "all": (get_network_access_conditions.asyncio_detailed, "get_network_access_conditions"),
            "policyset": (get_network_access_conditions_for_policy_set.asyncio_detailed, "get_network_access_conditions_for_policy_set"),
            "authentication": (get_network_access_conditions_for_authentication_rule.asyncio_detailed, "get_network_access_conditions_for_authentication_rule"),
            "authorization": (get_network_access_conditions_for_authorization_rule.asyncio_detailed, "get_network_access_conditions_for_authorization_rule"),
        }
        api_function, op_name = api_map[scope]
        response = await self.execute_api_call(
            api_function=api_function,
            operation_name=op_name,
        )
        return response.get("response", []) if isinstance(response, dict) else []

    async def get_network_access_identity_stores(self) -> list[dict[str, Any]]:
        response = await self.execute_api_call(
            api_function=get_network_access_identity_stores.asyncio_detailed,
            operation_name="get_network_access_identity_stores",
        )
        # Returns a JSON array directly.
        if isinstance(response, list):
            return response
        if isinstance(response, dict):
            return response.get("response", []) or []
        return []

    async def get_network_access_security_groups(self) -> list[dict[str, Any]]:
        response = await self.execute_api_call(
            api_function=get_network_access_security_groups.asyncio_detailed,
            operation_name="get_network_access_security_groups",
        )
        if isinstance(response, list):
            return response
        if isinstance(response, dict):
            return response.get("response", []) or []
        return []

    async def get_network_access_service_names(self) -> list[dict[str, Any]]:
        response = await self.execute_api_call(
            api_function=get_network_access_service_names.asyncio_detailed,
            operation_name="get_network_access_service_names",
        )
        if isinstance(response, list):
            return response
        if isinstance(response, dict):
            return response.get("response", []) or []
        return []

    # -----------------------------------------------------------------
    # Tool 1 — ise_search_policy_sets
    # -----------------------------------------------------------------

    async def search_policy_sets(
        self,
        name_substring: Optional[str] = None,
        state_filter: str = "all",
        limit: int = 50,
        min_hit_counts: Optional[int] = None,
        max_hit_counts: Optional[int] = None,
    ) -> PolicySetSearchResult:
        validated_limit = validate_limit(limit, max_limit=100)
        validated_state = validate_policy_set_state_filter(state_filter)
        validated_substring = (
            validate_name_substring(name_substring, field_name="name_substring")
            if name_substring is not None else None
        )
        validated_min_hits = validate_min_hit_counts(min_hit_counts)
        validated_max_hits = validate_max_hit_counts(max_hit_counts)
        validate_hit_counts_range(validated_min_hits, validated_max_hits)

        logger.info(
            "Searching policy sets",
            name_substring=validated_substring,
            state_filter=validated_state,
            limit=validated_limit,
            min_hit_counts=validated_min_hits,
            max_hit_counts=validated_max_hits,
        )

        raw_list = await self.get_network_access_policy_set_list()
        if not isinstance(raw_list, list):
            raw_list = []

        sorted_raw = _sort_policy_sets_by_rank(raw_list)
        matching = []
        for raw in sorted_raw:
            if not isinstance(raw, dict):
                continue
            state = _normalize_state(raw.get("state"))
            if not _state_filter_matches(state, validated_state):
                continue
            if not _name_matches(raw.get("name"), validated_substring):
                continue
            hits = raw.get("hitCounts") or 0
            if validated_min_hits is not None and hits < validated_min_hits:
                continue
            if validated_max_hits is not None and hits > validated_max_hits:
                continue
            matching.append(raw)

        total = len(matching)
        truncated = matching[:validated_limit]
        summaries = [_build_policy_set_summary(p) for p in truncated]

        search_filters: Dict[str, Any] = {
            "state_filter": validated_state,
            "limit": validated_limit,
        }
        if validated_substring is not None:
            search_filters["name_substring"] = validated_substring
        if validated_min_hits is not None:
            search_filters["min_hit_counts"] = validated_min_hits
        if validated_max_hits is not None:
            search_filters["max_hit_counts"] = validated_max_hits

        return PolicySetSearchResult(
            search_filters=search_filters,
            total_count=total,
            count=len(summaries),
            has_more=total > len(summaries),
            policy_sets=summaries,
        )

    # -----------------------------------------------------------------
    # Tool 2 — ise_get_policy_set_details
    # -----------------------------------------------------------------

    async def _resolve_policy_set_id_by_name(self, policy_set_name: str) -> tuple[str, Dict[str, Any]]:
        """Resolve a policy-set name to its (id, raw_dict).

        Raises NOT_FOUND ToolError when no policy set with that name exists.
        """
        raw_list = await self.get_network_access_policy_set_list()
        if not isinstance(raw_list, list):
            raw_list = []
        for raw in raw_list:
            if isinstance(raw, dict) and raw.get("name") == policy_set_name:
                ps_id = raw.get("id")
                if not ps_id:
                    raise_tool_error(
                        ErrorCategory.EXTERNAL_ERROR,
                        "ISE_INVALID_RESPONSE",
                        f"Policy set '{policy_set_name}' was found but has no id field in the ISE response.",
                        retry=False,
                    )
                return str(ps_id), raw
        raise_tool_error(
            ErrorCategory.CLIENT_ERROR,
            "POLICY_SET_NOT_FOUND",
            f"Policy set '{policy_set_name}' not found. Use ise_search_policy_sets to discover available policy set names.",
            retry=False,
        )
        # Unreachable — raise_tool_error always raises; keeps mypy happy.
        return "", {}

    async def get_policy_set_details(
        self,
        policy_set_name: str,
        rules_per_section_limit: int = 10,
    ) -> PolicySetDetailsResult:
        validated_name = validate_policy_set_name(policy_set_name)
        validated_section_limit = validate_limit(rules_per_section_limit, max_limit=25)

        logger.info(
            "Fetching policy set details",
            policy_set_name=validated_name,
            rules_per_section_limit=validated_section_limit,
        )

        policy_id, _ = await self._resolve_policy_set_id_by_name(validated_name)

        # Parallel fan-out for the four detail endpoints.
        ps_detail_task = self.get_network_access_policy_set_by_id(policy_id)
        authn_task = self.get_network_access_authentication_rule_list(policy_id)
        authz_task = self.get_network_access_authorization_rule_list(policy_id)
        local_exc_task = self.get_network_access_local_exception_rule_list(policy_id)

        ps_detail_raw, authn_raw, authz_raw, local_exc_raw = await asyncio.gather(
            ps_detail_task, authn_task, authz_task, local_exc_task,
        )

        # The by-id endpoint returns the policy set directly under "response".
        # When ISE wraps it differently we still try to coerce gracefully.
        if isinstance(ps_detail_raw, dict) and "name" not in ps_detail_raw:
            inner = ps_detail_raw.get("response")
            if isinstance(inner, dict):
                ps_detail_raw = inner
        if not isinstance(ps_detail_raw, dict) or not ps_detail_raw:
            # Fall back to the data we already have from list resolution.
            _, ps_detail_raw = await self._resolve_policy_set_id_by_name(validated_name)

        ps_summary = _build_policy_set_summary(ps_detail_raw)

        authn_sorted = _sort_by_rank(authn_raw if isinstance(authn_raw, list) else [])
        authn_total = len(authn_sorted)
        authn_truncated = authn_sorted[:validated_section_limit]
        authn_section = AuthenticationRulesSection(
            total_count=authn_total,
            count=len(authn_truncated),
            has_more=authn_total > len(authn_truncated),
            rules=[_build_authn_rule_summary(e) for e in authn_truncated],
        )

        authz_sorted = _sort_by_rank(authz_raw if isinstance(authz_raw, list) else [])
        authz_total = len(authz_sorted)
        authz_truncated = authz_sorted[:validated_section_limit]
        authz_section = AuthorizationRulesSection(
            total_count=authz_total,
            count=len(authz_truncated),
            has_more=authz_total > len(authz_truncated),
            rules=[_build_authz_rule_summary(e) for e in authz_truncated],
        )

        local_exc_sorted = _sort_by_rank(local_exc_raw if isinstance(local_exc_raw, list) else [])
        local_exc_total = len(local_exc_sorted)
        local_exc_truncated = local_exc_sorted[:validated_section_limit]
        local_exc_section = LocalExceptionRulesSection(
            total_count=local_exc_total,
            count=len(local_exc_truncated),
            has_more=local_exc_total > len(local_exc_truncated),
            rules=[_build_authz_rule_summary(e) for e in local_exc_truncated],
        )

        return PolicySetDetailsResult(
            policy_set=ps_summary,
            authentication_rules=authn_section,
            authorization_rules=authz_section,
            local_exception_rules=local_exc_section,
        )

    # -----------------------------------------------------------------
    # Tool 3 — ise_search_authorization_rules
    # -----------------------------------------------------------------

    async def search_authorization_rules(
        self,
        policy_set_name: Optional[str] = None,
        profile_name_filter: Optional[str] = None,
        security_group_filter: Optional[str] = None,
        state_filter: str = "all",
        min_hit_counts: Optional[int] = None,
        name_substring: Optional[str] = None,
        limit: int = 25,
    ) -> AuthorizationRuleSearchResult:
        validated_limit = validate_limit(limit, max_limit=50)
        validated_state = validate_rule_state_filter(state_filter)
        validated_min_hits = validate_min_hit_counts(min_hit_counts)
        validated_policy_set_name = (
            validate_policy_set_name(policy_set_name) if policy_set_name is not None else None
        )
        validated_profile = (
            validate_name_substring(profile_name_filter, field_name="profile_name_filter")
            if profile_name_filter is not None else None
        )
        validated_sg = (
            validate_name_substring(security_group_filter, field_name="security_group_filter")
            if security_group_filter is not None else None
        )
        validated_substring = (
            validate_name_substring(name_substring, field_name="name_substring")
            if name_substring is not None else None
        )

        logger.info(
            "Searching authorization rules",
            policy_set_name=validated_policy_set_name,
            profile_name_filter=validated_profile,
            security_group_filter=validated_sg,
            state_filter=validated_state,
            min_hit_counts=validated_min_hits,
            name_substring=validated_substring,
            limit=validated_limit,
        )

        # Determine the per-policy-set fan-out target list.
        policy_sets_to_scan: List[Dict[str, Any]]
        if validated_policy_set_name is not None:
            ps_id, ps_raw = await self._resolve_policy_set_id_by_name(validated_policy_set_name)
            policy_sets_to_scan = [ps_raw]
        else:
            raw_list = await self.get_network_access_policy_set_list()
            if not isinstance(raw_list, list):
                raw_list = []
            sorted_raw = _sort_policy_sets_by_rank([p for p in raw_list if isinstance(p, dict)])
            policy_sets_to_scan = sorted_raw[:_MAX_FAN_OUT_POLICY_SETS]

        # Issue per-policy-set authz fetches and the global-exception fetch in parallel.
        per_ps_tasks = [
            self.get_network_access_authorization_rule_list(str(ps.get("id")))
            for ps in policy_sets_to_scan
            if ps.get("id")
        ]
        global_exc_task = self.get_network_access_global_exception_rule_list()

        results = await asyncio.gather(
            *per_ps_tasks, global_exc_task, return_exceptions=False,
        )
        per_ps_results = results[:-1]
        global_exc_raw = results[-1] if results else []

        rules: List[AuthorizationRuleHit] = []
        for ps, ps_rules in zip(policy_sets_to_scan, per_ps_results):
            ps_name = ps.get("name") or ""
            for entry in (ps_rules if isinstance(ps_rules, list) else []):
                if not isinstance(entry, dict):
                    continue
                hit = self._build_authz_rule_hit(entry, policy_set_name=ps_name)
                if not self._authz_hit_passes_filters(
                    hit, entry, validated_state, validated_min_hits,
                    validated_profile, validated_sg, validated_substring,
                ):
                    continue
                rules.append(hit)

        rules_total = len(rules)
        rules_truncated = rules[:validated_limit]

        global_exceptions: List[AuthorizationRuleHit] = []
        for entry in (global_exc_raw if isinstance(global_exc_raw, list) else []):
            if not isinstance(entry, dict):
                continue
            hit = self._build_authz_rule_hit(entry, policy_set_name=None)
            if not self._authz_hit_passes_filters(
                hit, entry, validated_state, validated_min_hits,
                validated_profile, validated_sg, validated_substring,
            ):
                continue
            global_exceptions.append(hit)

        search_filters: Dict[str, Any] = {
            "state_filter": validated_state,
            "limit": validated_limit,
        }
        if validated_policy_set_name is not None:
            search_filters["policy_set_name"] = validated_policy_set_name
        if validated_profile is not None:
            search_filters["profile_name_filter"] = validated_profile
        if validated_sg is not None:
            search_filters["security_group_filter"] = validated_sg
        if validated_min_hits is not None:
            search_filters["min_hit_counts"] = validated_min_hits
        if validated_substring is not None:
            search_filters["name_substring"] = validated_substring

        return AuthorizationRuleSearchResult(
            search_filters=search_filters,
            total_count=rules_total,
            count=len(rules_truncated),
            has_more=rules_total > len(rules_truncated),
            policy_sets_scanned=len(policy_sets_to_scan),
            rules=rules_truncated,
            global_exceptions=global_exceptions,
        )

    @staticmethod
    def _build_authz_rule_hit(entry: Dict[str, Any], *, policy_set_name: Optional[str]) -> AuthorizationRuleHit:
        rule = entry.get("rule") or {}
        return AuthorizationRuleHit(
            policy_set_name=policy_set_name,
            name=rule.get("name") or "",
            rank=rule.get("rank"),
            state=_normalize_state(rule.get("state")),
            hit_counts=rule.get("hitCounts"),
            profile=entry.get("profile"),
            security_group=entry.get("securityGroup"),
            condition_summary=condition_to_summary(rule.get("condition")),
        )

    @staticmethod
    def _authz_hit_passes_filters(
        hit: AuthorizationRuleHit,
        entry: Dict[str, Any],
        state_filter: str,
        min_hit_counts: Optional[int],
        profile_substring: Optional[str],
        sg_substring: Optional[str],
        name_substring: Optional[str],
    ) -> bool:
        if not _state_filter_matches(hit.state, state_filter):
            return False
        if min_hit_counts is not None and (hit.hit_counts or 0) < min_hit_counts:
            return False
        if not _name_matches(hit.name, name_substring):
            return False
        if not _profile_list_matches(entry.get("profile"), profile_substring):
            return False
        if not _security_group_matches(entry.get("securityGroup"), sg_substring):
            return False
        return True

    # -----------------------------------------------------------------
    # Tool 4 — ise_search_authentication_rules
    # -----------------------------------------------------------------

    async def search_authentication_rules(
        self,
        policy_set_name: Optional[str] = None,
        identity_source_filter: Optional[str] = None,
        state_filter: str = "all",
        min_hit_counts: Optional[int] = None,
        name_substring: Optional[str] = None,
        limit: int = 25,
    ) -> AuthenticationRuleSearchResult:
        validated_limit = validate_limit(limit, max_limit=50)
        validated_state = validate_rule_state_filter(state_filter)
        validated_min_hits = validate_min_hit_counts(min_hit_counts)
        validated_policy_set_name = (
            validate_policy_set_name(policy_set_name) if policy_set_name is not None else None
        )
        validated_identity_source = (
            validate_name_substring(identity_source_filter, field_name="identity_source_filter")
            if identity_source_filter is not None else None
        )
        validated_substring = (
            validate_name_substring(name_substring, field_name="name_substring")
            if name_substring is not None else None
        )

        logger.info(
            "Searching authentication rules",
            policy_set_name=validated_policy_set_name,
            identity_source_filter=validated_identity_source,
            state_filter=validated_state,
            min_hit_counts=validated_min_hits,
            name_substring=validated_substring,
            limit=validated_limit,
        )

        if validated_policy_set_name is not None:
            _, ps_raw = await self._resolve_policy_set_id_by_name(validated_policy_set_name)
            policy_sets_to_scan = [ps_raw]
        else:
            raw_list = await self.get_network_access_policy_set_list()
            if not isinstance(raw_list, list):
                raw_list = []
            sorted_raw = _sort_policy_sets_by_rank([p for p in raw_list if isinstance(p, dict)])
            policy_sets_to_scan = sorted_raw[:_MAX_FAN_OUT_POLICY_SETS]

        tasks = [
            self.get_network_access_authentication_rule_list(str(ps.get("id")))
            for ps in policy_sets_to_scan
            if ps.get("id")
        ]
        per_ps_results = await asyncio.gather(*tasks)

        rules: List[AuthenticationRuleHit] = []
        for ps, ps_rules in zip(policy_sets_to_scan, per_ps_results):
            ps_name = ps.get("name") or ""
            for entry in (ps_rules if isinstance(ps_rules, list) else []):
                if not isinstance(entry, dict):
                    continue
                hit = self._build_authn_rule_hit(entry, policy_set_name=ps_name)
                if not self._authn_hit_passes_filters(
                    hit, entry, validated_state, validated_min_hits,
                    validated_identity_source, validated_substring,
                ):
                    continue
                rules.append(hit)

        total = len(rules)
        truncated = rules[:validated_limit]

        search_filters: Dict[str, Any] = {
            "state_filter": validated_state,
            "limit": validated_limit,
        }
        if validated_policy_set_name is not None:
            search_filters["policy_set_name"] = validated_policy_set_name
        if validated_identity_source is not None:
            search_filters["identity_source_filter"] = validated_identity_source
        if validated_min_hits is not None:
            search_filters["min_hit_counts"] = validated_min_hits
        if validated_substring is not None:
            search_filters["name_substring"] = validated_substring

        return AuthenticationRuleSearchResult(
            search_filters=search_filters,
            total_count=total,
            count=len(truncated),
            has_more=total > len(truncated),
            policy_sets_scanned=len(policy_sets_to_scan),
            rules=truncated,
        )

    @staticmethod
    def _build_authn_rule_hit(entry: Dict[str, Any], *, policy_set_name: str) -> AuthenticationRuleHit:
        rule = entry.get("rule") or {}
        return AuthenticationRuleHit(
            policy_set_name=policy_set_name,
            name=rule.get("name") or "",
            rank=rule.get("rank"),
            state=_normalize_state(rule.get("state")),
            hit_counts=rule.get("hitCounts"),
            identity_source_name=entry.get("identitySourceName"),
            if_auth_fail=entry.get("ifAuthFail"),
            if_user_not_found=entry.get("ifUserNotFound"),
            if_process_fail=entry.get("ifProcessFail"),
            condition_summary=condition_to_summary(rule.get("condition")),
        )

    @staticmethod
    def _authn_hit_passes_filters(
        hit: AuthenticationRuleHit,
        entry: Dict[str, Any],
        state_filter: str,
        min_hit_counts: Optional[int],
        identity_source_substring: Optional[str],
        name_substring: Optional[str],
    ) -> bool:
        if not _state_filter_matches(hit.state, state_filter):
            return False
        if min_hit_counts is not None and (hit.hit_counts or 0) < min_hit_counts:
            return False
        if not _name_matches(hit.name, name_substring):
            return False
        if not _identity_source_matches(entry.get("identitySourceName"), identity_source_substring):
            return False
        return True

    # -----------------------------------------------------------------
    # Tool 5 — ise_search_authorization_profiles
    # -----------------------------------------------------------------

    async def search_authorization_profiles(
        self,
        name_substring: Optional[str] = None,
        limit: int = 50,
    ) -> AuthorizationProfileSearchResult:
        validated_limit = validate_limit(limit, max_limit=200)
        validated_substring = (
            validate_name_substring(name_substring, field_name="name_substring")
            if name_substring is not None else None
        )

        logger.info(
            "Searching authorization profiles",
            name_substring=validated_substring,
            limit=validated_limit,
        )

        raw_list = await self.get_network_access_authorization_profiles()
        if not isinstance(raw_list, list):
            raw_list = []

        matching = []
        for raw in raw_list:
            if not isinstance(raw, dict):
                continue
            if not _name_matches(raw.get("name"), validated_substring):
                continue
            matching.append(raw)

        matching.sort(key=lambda p: (p.get("name") or "").lower())

        total = len(matching)
        truncated = matching[:validated_limit]
        profiles = [
            AuthorizationProfileSummary(
                name=p.get("name") or "",
                description=p.get("description"),
            )
            for p in truncated
        ]

        search_filters: Dict[str, Any] = {"limit": validated_limit}
        if validated_substring is not None:
            search_filters["name_substring"] = validated_substring

        return AuthorizationProfileSearchResult(
            search_filters=search_filters,
            total_count=total,
            count=len(profiles),
            has_more=total > len(profiles),
            profiles=profiles,
        )

    # -----------------------------------------------------------------
    # Tool 6 — ise_search_library_conditions
    # -----------------------------------------------------------------

    async def search_library_conditions(
        self,
        name_substring: Optional[str] = None,
        scope_filter: str = "all",
        limit: int = 25,
    ) -> LibraryConditionSearchResult:
        validated_limit = validate_limit(limit, max_limit=50)
        validated_scope = validate_condition_scope_filter(scope_filter)
        validated_substring = (
            validate_name_substring(name_substring, field_name="name_substring")
            if name_substring is not None else None
        )

        logger.info(
            "Searching library conditions",
            name_substring=validated_substring,
            scope_filter=validated_scope,
            limit=validated_limit,
        )

        raw_list = await self.get_network_access_library_conditions(scope=validated_scope)
        if not isinstance(raw_list, list):
            raw_list = []

        matching = []
        for raw in raw_list:
            if not isinstance(raw, dict):
                continue
            if not _name_matches(raw.get("name"), validated_substring):
                continue
            matching.append(raw)

        matching.sort(key=lambda c: (c.get("name") or "").lower())

        total = len(matching)
        truncated = matching[:validated_limit]
        conditions = [
            LibraryConditionSummary(
                name=c.get("name") or "",
                description=c.get("description"),
                condition_summary=condition_to_summary(c),
            )
            for c in truncated
        ]

        search_filters: Dict[str, Any] = {
            "scope_filter": validated_scope,
            "limit": validated_limit,
        }
        if validated_substring is not None:
            search_filters["name_substring"] = validated_substring

        return LibraryConditionSearchResult(
            search_filters=search_filters,
            total_count=total,
            count=len(conditions),
            has_more=total > len(conditions),
            conditions=conditions,
        )

    # -----------------------------------------------------------------
    # Tool 7 — ise_list_policy_authoring_references
    # -----------------------------------------------------------------

    async def list_policy_authoring_references(
        self,
        name_substring: Optional[str] = None,
        limit_per_section: int = 50,
    ) -> PolicyAuthoringReferencesResult:
        validated_limit = validate_limit(limit_per_section, max_limit=200)
        validated_substring = (
            validate_name_substring(name_substring, field_name="name_substring")
            if name_substring is not None else None
        )

        logger.info(
            "Listing policy authoring references",
            name_substring=validated_substring,
            limit_per_section=validated_limit,
        )

        identity_stores_raw, security_groups_raw, service_names_raw = await asyncio.gather(
            self.get_network_access_identity_stores(),
            self.get_network_access_security_groups(),
            self.get_network_access_service_names(),
        )

        identity_stores_section = self._build_identity_stores_section(
            identity_stores_raw, validated_substring, validated_limit,
        )
        security_groups_section = self._build_security_groups_section(
            security_groups_raw, validated_substring, validated_limit,
        )
        service_names_section = self._build_service_names_section(
            service_names_raw, validated_substring, validated_limit,
        )

        search_filters: Dict[str, Any] = {"limit_per_section": validated_limit}
        if validated_substring is not None:
            search_filters["name_substring"] = validated_substring

        return PolicyAuthoringReferencesResult(
            search_filters=search_filters,
            identity_stores=identity_stores_section,
            security_groups=security_groups_section,
            service_names=service_names_section,
        )

    @staticmethod
    def _build_identity_stores_section(
        raw_list: Any,
        substring: Optional[str],
        limit: int,
    ) -> IdentityStoresSection:
        items_raw = raw_list if isinstance(raw_list, list) else []
        matching = [
            r for r in items_raw
            if isinstance(r, dict) and _name_matches(r.get("name"), substring)
        ]
        matching.sort(key=lambda r: (r.get("name") or "").lower())
        total = len(matching)
        truncated = matching[:limit]
        items = [IdentityStoreSummary(name=r.get("name") or "") for r in truncated]
        return IdentityStoresSection(
            total_count=total,
            count=len(items),
            has_more=total > len(items),
            items=items,
        )

    @staticmethod
    def _build_security_groups_section(
        raw_list: Any,
        substring: Optional[str],
        limit: int,
    ) -> SecurityGroupsSection:
        items_raw = raw_list if isinstance(raw_list, list) else []
        matching = [
            r for r in items_raw
            if isinstance(r, dict) and _name_matches(r.get("name"), substring)
        ]
        matching.sort(key=lambda r: (r.get("name") or "").lower())
        total = len(matching)
        truncated = matching[:limit]
        items = [SecurityGroupSummary(name=r.get("name") or "") for r in truncated]
        return SecurityGroupsSection(
            total_count=total,
            count=len(items),
            has_more=total > len(items),
            items=items,
        )

    @staticmethod
    def _build_service_names_section(
        raw_list: Any,
        substring: Optional[str],
        limit: int,
    ) -> ServiceNamesSection:
        items_raw = raw_list if isinstance(raw_list, list) else []
        matching = [
            r for r in items_raw
            if isinstance(r, dict) and _name_matches(r.get("name"), substring)
        ]
        matching.sort(key=lambda r: (r.get("name") or "").lower())
        total = len(matching)
        truncated = matching[:limit]

        items: List[ServiceNameSummary] = []
        for r in truncated:
            raw_type = r.get("serviceType") or r.get("service_type")
            normalized_type: Optional[str]
            if isinstance(raw_type, str):
                lowered = raw_type.strip().lower().replace("-", "_").replace(" ", "_")
                if "server" in lowered and "sequence" in lowered:
                    normalized_type = "server_sequence"
                elif "allowed" in lowered or "protocol" in lowered:
                    normalized_type = "allowed_protocols"
                else:
                    normalized_type = None
            else:
                normalized_type = None
            items.append(
                ServiceNameSummary(
                    name=r.get("name") or "",
                    service_type=normalized_type,  # type: ignore[arg-type]
                    is_local_authorization=r.get("isLocalAuthorization"),
                )
            )
        return ServiceNamesSection(
            total_count=total,
            count=len(items),
            has_more=total > len(items),
            items=items,
        )
